#!/usr/bin/env python3
"""
Generates migrations/0013_seed_writing_test_bank.sql from:
  - scripts/r2-writing-seed/manifest.json     (task text, per test)
  - scripts/r2-writing-seed/image-urls.json   (R2 public URL per test, from upload-to-r2.mjs)

Follows the exact same model as the original seed_writing_test_1.sql:
  * 1 row in `tests` per writing set (skill='writing')
  * test_resources: task_prompt/1 (Task1 text), task_image/1 (Task1 chart),
    task_prompt/2 (Task2 text) — no image for Task2.

Run from repo root:
    python3 scripts/r2-writing-seed/generate_seed_sql.py
"""
import json
import re
import uuid
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent.parent
SEED_DIR = Path(__file__).resolve().parent
OUT_PATH = ROOT / "migrations" / "0013_seed_writing_test_bank.sql"

# Fixed namespace so re-running this script regenerates the SAME UUIDs
# every time (idempotent — ON CONFLICT DO UPDATE keys off these ids).
NAMESPACE = uuid.UUID("22222222-2222-2222-2222-222222222222")


def test_uuid(n: int) -> str:
    return str(uuid.uuid5(NAMESPACE, f"writing-test-{n}"))


def sql_quote(s: str) -> str:
    return "'" + s.replace("'", "''") + "'"


def short_description(task1: str, question_type: str | None) -> str:
    # First clause of the Task 1 prompt, trimmed, plus the question type.
    first_sentence = re.split(r"\.\s", task1, maxsplit=1)[0]
    first_sentence = first_sentence[:140].rstrip()
    qt = f" Task 2: {question_type}." if question_type else ""
    return f"{first_sentence}...{qt}".strip()


def main():
    manifest = json.loads((SEED_DIR / "manifest.json").read_text(encoding="utf-8"))
    urls_path = SEED_DIR / "image-urls.json"
    if not urls_path.exists():
        raise SystemExit(
            "image-urls.json not found — run upload-to-r2.mjs first "
            "(it writes this file after uploading all images)."
        )
    urls = json.loads(urls_path.read_text(encoding="utf-8"))

    missing = [e["num"] for e in manifest if str(e["num"]) not in urls]
    if missing:
        raise SystemExit(f"Missing R2 URLs for test numbers: {missing}")

    lines = []
    lines.append("-- =====================================================================")
    lines.append("-- Migration 0013 — Seed the full IELTS Writing test bank (70 sets)")
    lines.append("-- Generated by scripts/r2-writing-seed/generate_seed_sql.py — do not")
    lines.append("-- hand-edit; re-run the generator instead if the source data changes.")
    lines.append("--")
    lines.append("-- Model (same as the original seed_writing_test_1.sql):")
    lines.append("--   * 1 row in `tests`      -> the writing set (skill='writing')")
    lines.append("--   * `test_resources` rows -> task_prompt/1, task_image/1, task_prompt/2")
    lines.append("--")
    lines.append("-- Run: psql \"$DATABASE_URL\" -f migrations/0013_seed_writing_test_bank.sql")
    lines.append("-- Idempotent: re-running replaces each test's resources cleanly.")
    lines.append("-- =====================================================================")
    lines.append("")
    lines.append("BEGIN;")
    lines.append("")

    for entry in manifest:
        n = entry["num"]
        tid = test_uuid(n)
        image_url = urls[str(n)]
        task1 = entry["task1"]
        task2 = entry["task2"]
        qtype = entry.get("question_type")
        title = f"IELTS Writing Mock Test {n}"
        description = short_description(task1, qtype)
        instructions = (
            "Complete both tasks. Task 1: write at least 150 words. "
            "Task 2: write at least 250 words. You should spend about 20 "
            "minutes on Task 1 and 40 minutes on Task 2."
        )

        lines.append(f"-- ---- Mock Test {n} " + "-" * max(0, 50 - len(str(n))))
        lines.append("DO $$")
        lines.append("DECLARE")
        lines.append(f"    v_test_id UUID := {sql_quote(tid)};")
        lines.append(f"    v_image_url TEXT := {sql_quote(image_url)};")
        lines.append("BEGIN")
        lines.append("    INSERT INTO tests (id, skill, title, description, instructions, duration_seconds, position, is_published)")
        lines.append("    VALUES (")
        lines.append("        v_test_id,")
        lines.append("        'writing',")
        lines.append(f"        {sql_quote(title)},")
        lines.append(f"        {sql_quote(description)},")
        lines.append(f"        {sql_quote(instructions)},")
        lines.append("        3600,")
        lines.append(f"        {n},")
        lines.append("        TRUE")
        lines.append("    )")
        lines.append("    ON CONFLICT (id) DO UPDATE")
        lines.append("        SET title = EXCLUDED.title,")
        lines.append("            description = EXCLUDED.description,")
        lines.append("            instructions = EXCLUDED.instructions,")
        lines.append("            duration_seconds = EXCLUDED.duration_seconds,")
        lines.append("            position = EXCLUDED.position,")
        lines.append("            is_published = EXCLUDED.is_published,")
        lines.append("            updated_at = now();")
        lines.append("")
        lines.append("    DELETE FROM test_resources WHERE test_id = v_test_id;")
        lines.append("")
        lines.append("    INSERT INTO test_resources (test_id, kind, content, position)")
        lines.append(f"    VALUES (v_test_id, 'task_prompt', {sql_quote(task1)}, 1);")
        lines.append("")
        lines.append("    INSERT INTO test_resources (test_id, kind, url, position)")
        lines.append("    VALUES (v_test_id, 'task_image', v_image_url, 1);")
        lines.append("")
        lines.append("    INSERT INTO test_resources (test_id, kind, content, position)")
        lines.append(f"    VALUES (v_test_id, 'task_prompt', {sql_quote(task2)}, 2);")
        lines.append("END $$;")
        lines.append("")

    lines.append("COMMIT;")

    OUT_PATH.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {OUT_PATH} ({len(manifest)} tests)")


if __name__ == "__main__":
    main()
