-- 0005_add_diagnostic_test.sql

INSERT INTO "tests" (
  "id", 
  "skill", 
  "title", 
  "instructions", 
  "band_target", 
  "duration_seconds", 
  "position", 
  "is_published"
)
VALUES 
  (gen_random_uuid(), 'writing', 'IELTS Diagnostic Test - Writing Task 2', 'Complete the Task 2 essay generated by AI.', 7.0, 2400, 1, true),
  (gen_random_uuid(), 'reading', 'IELTS Diagnostic Test - Reading', 'Answer the diagnostic reading questions.', 7.0, 900, 2, true),
  (gen_random_uuid(), 'listening', 'IELTS Diagnostic Test - Listening', 'Listen and complete the diagnostic listening tasks.', 7.0, 900, 3, true),
  (gen_random_uuid(), 'speaking', 'IELTS Diagnostic Test - Speaking', 'Respond to the dynamic AI speaking prompts.', 7.0, 600, 4, true)
ON CONFLICT DO NOTHING;