-- =====================================================================
-- Fix: 74 reading test multiple-choice questions had options B, C, D
-- merged into a single option's text field instead of being separate
-- array entries (a splitting bug during content generation for
-- migrations/0015_seed_reading_test_bank.sql). This caused the frontend
-- to render one giant text blob instead of four selectable choices.
-- Safe to re-run.
-- =====================================================================
BEGIN;

UPDATE test_questions SET options = '[{"letter": "A", "text": "To replace elected politicians with certified academic experts."}, {"letter": "B", "text": "To create policy decisions through inclusive and reasoned citizen discussion."}, {"letter": "C", "text": "To accelerate government decision-making by eliminating public voting."}, {"letter": "D", "text": "To ensure that technical specialists have the final authority over legislation."}]'::jsonb WHERE id = '39b7543a-0164-561a-9d61-2e472ff5ef70';
UPDATE test_questions SET options = '[{"letter": "A", "text": "It involves the direct physical intimidation of marginalized speakers in forums."}, {"letter": "B", "text": "It occurs when a speaker''s statements are judged solely on statistical data."}, {"letter": "C", "text": "It stems from a structural lack of shared concepts to explain social experiences."}, {"letter": "D", "text": "It results exclusively from deliberate financial corruption within political parties."}]'::jsonb WHERE id = '97c5bfcf-2abb-5b93-989a-f7e6dff9a4d5';
UPDATE test_questions SET options = '[{"letter": "A", "text": "participants with lower socioeconomic status dominate group discussions."}, {"letter": "B", "text": "achieving demographic representation automatically ensures equal influence."}, {"letter": "C", "text": "personal narratives are universally accepted as superior to scientific evidence."}, {"letter": "D", "text": "participants from privileged backgrounds receive higher levels of credibility."}]'::jsonb WHERE id = '572c1c1f-1994-5144-a814-65f650577efa';
UPDATE test_questions SET options = '[{"letter": "A", "text": "removing all expert witnesses from citizens'' assemblies."}, {"letter": "B", "text": "relying on neutral moderators and structured discourse rules."}, {"letter": "C", "text": "banning any discussion of complex or technical policy issues."}, {"letter": "D", "text": "allowing only written submissions rather than oral debates."}]'::jsonb WHERE id = 'db2c1232-fded-56af-816e-0442c3762bad';
UPDATE test_questions SET options = '[{"letter": "A", "text": "favor the communicative habits of dominant social groups."}, {"letter": "B", "text": "make discussions take too much time to reach a consensus."}, {"letter": "C", "text": "are too simple to address complex scientific problems."}, {"letter": "D", "text": "force all participants to express their ideas through emotional stories."}]'::jsonb WHERE id = 'd453d60b-30af-5107-b799-06cae396d47c';
UPDATE test_questions SET options = '[{"letter": "A", "text": "the primary cognitive mechanism behind abstract human thought."}, {"letter": "B", "text": "a decorative linguistic feature that had little importance to literal truth."}, {"letter": "C", "text": "an unreliable communicative obstacle that caused semantic drift."}, {"letter": "D", "text": "a system of mathematical symbols representing physical objects."}]'::jsonb WHERE id = '634ac58b-92e8-5e2a-9a6b-37e6673508d2';
UPDATE test_questions SET options = '[{"letter": "A", "text": "To deliberately confuse political opponents during formal debates."}, {"letter": "B", "text": "To demonstrate mastery of artistic and poetic speech in literature."}, {"letter": "C", "text": "To comprehend abstract ideas through familiar concrete experiences."}, {"letter": "D", "text": "To replace complex spoken grammar with simple visual signs."}]'::jsonb WHERE id = '5dea073d-e4ef-5c9f-a4c1-a189bf52c238';
UPDATE test_questions SET options = '[{"letter": "A", "text": "Metaphorical descriptions of crime directly influenced what solutions people proposed."}, {"letter": "B", "text": "Citizens pay more attention to crime statistics than to metaphorical descriptions."}, {"letter": "C", "text": "Describing crime as a virus caused people to demand stricter prison sentences."}, {"letter": "D", "text": "Public opinion on crime cannot be shifted by changing language choices."}]'::jsonb WHERE id = 'a5cfcd5c-b982-576c-9bda-42fd3af8165c';
UPDATE test_questions SET options = '[{"letter": "A", "text": "how ancient Latin words were entirely abandoned in modern Europe."}, {"letter": "B", "text": "why abstract thinking causes individuals to lose their physical senses."}, {"letter": "C", "text": "how physical actions evolved into abstract intellectual meanings over time."}, {"letter": "D", "text": "why grammatical rules decay when languages are translated across cultures."}]'::jsonb WHERE id = 'b885308f-cc68-571c-b910-acfc95d76b70';
UPDATE test_questions SET options = '[{"letter": "A", "text": "It relied on manufactured examples rather than real-world language use."}, {"letter": "B", "text": "It failed to identify any relationship between language and human culture."}, {"letter": "C", "text": "It completely rejected the existence of idioms in European languages."}, {"letter": "D", "text": "It argued that the human brain lacks the ability to process metaphors."}]'::jsonb WHERE id = '5897fa03-6999-504a-a8ee-b0b41090c1e3';
UPDATE test_questions SET options = '[{"letter": "A", "text": "Living organisms lack the chemical compounds necessary to produce electrons."}, {"letter": "B", "text": "Cells operate at warm temperatures and contain chaotic fluids that cause decoherence."}, {"letter": "C", "text": "Quantum mechanics was thought to apply only to celestial bodies and astronomy."}, {"letter": "D", "text": "Biological structures are too small to be analyzed by physical instruments."}]'::jsonb WHERE id = '0a42973f-6229-56f7-8a0b-25bf694c7c63';
UPDATE test_questions SET options = '[{"letter": "A", "text": "bounce randomly between molecules until it loses all of its thermal energy."}, {"letter": "B", "text": "move along all possible routes simultaneously to find the most efficient path."}, {"letter": "C", "text": "convert light directly into electrical current without entering a reaction center."}, {"letter": "D", "text": "escape the protein matrix and interact with outside water molecules."}]'::jsonb WHERE id = '38b57245-e69e-5940-b67b-437e835b34e0';
UPDATE test_questions SET options = '[{"letter": "A", "text": "the destructive noise of water molecules breaking down delicate plant tissues."}, {"letter": "B", "text": "the complete failure of excitons to reach photosynthetic reaction centers."}, {"letter": "C", "text": "the way protein vibrations help maintain and support quantum coherence."}, {"letter": "D", "text": "the mechanical movement of whole bacteria swimming toward sunlight."}]'::jsonb WHERE id = 'cf75fd02-506d-5a0c-a120-14ee4cb615a4';
UPDATE test_questions SET options = '[{"letter": "A", "text": "detecting Earth''s geomagnetic field through a light-sensitive eye protein."}, {"letter": "B", "text": "relying entirely on large deposits of mechanical iron in their beaks."}, {"letter": "C", "text": "listening to low-frequency sound waves reflected off mountain ranges."}, {"letter": "D", "text": "memorizing physical landmarks along coastal shorelines during daylight."}]'::jsonb WHERE id = '36a04957-168a-580a-9256-faac56e4f3e2';
UPDATE test_questions SET options = '[{"letter": "A", "text": "It induces physical electric shocks that trigger muscle movements in the wings."}, {"letter": "B", "text": "Magnetic field angles influence the transition between quantum spin states, altering chemical yields."}, {"letter": "C", "text": "It aligns physical iron particles to point the bird''s head toward the North Pole."}, {"letter": "D", "text": "It destroys cryptochrome molecules completely, signaling directional changes to the brain."}]'::jsonb WHERE id = 'a72e4f0a-6d13-54dd-86fe-2664f2c12e8d';
UPDATE test_questions SET options = '[{"letter": "A", "text": "environmental stress can directly modify DNA sequences in a deliberate direction."}, {"letter": "B", "text": "acquired characteristics developed during a lifetime cannot be inherited by offspring."}, {"letter": "C", "text": "physical traits are determined entirely by non-coding RNA molecules."}, {"letter": "D", "text": "natural selection plays a minor role in driving biological evolution."}]'::jsonb WHERE id = 'fb38a95b-9c57-521b-9c9c-b37556c38490';
UPDATE test_questions SET options = '[{"letter": "A", "text": "To rewrite the underlying primary nucleotide sequence of DNA."}, {"letter": "B", "text": "To create new genes out of amino acid chains in the cytoplasm."}, {"letter": "C", "text": "To control whether existing genes are actively expressed or silenced."}, {"letter": "D", "text": "To permanently destroy harmful chromosomes during cell division."}]'::jsonb WHERE id = 'f479b974-ab19-5f7c-92ec-9baff9b659f0';
UPDATE test_questions SET options = '[{"letter": "A", "text": "Mammals do not possess any non-coding RNA in their cells."}, {"letter": "B", "text": "Epigenetic marks are thoroughly erased and reset during two distinct developmental stages."}, {"letter": "C", "text": "DNA methylation occurs only in plants and cold-blooded animals."}, {"letter": "D", "text": "Sperm cells are incapable of carrying epigenetic information."}]'::jsonb WHERE id = '83966785-acb9-5adc-85b9-8280282cce69';
UPDATE test_questions SET options = '[{"letter": "A", "text": "showed a strong fear response to an odor their grandparents were trained to fear."}, {"letter": "B", "text": "failed to develop functioning odorant receptor genes in their brains."}, {"letter": "C", "text": "required continuous electric shocks to learn how to avoid the floral smell."}, {"letter": "D", "text": "lost all inherited epigenetic marks after being exposed to the odor."}]'::jsonb WHERE id = 'a43ceb99-697f-503f-95eb-3b6afc76572a';
UPDATE test_questions SET options = '[{"letter": "A", "text": "were completely immune to metabolic and cardiovascular diseases."}, {"letter": "B", "text": "inherited permanent mutations in their primary DNA sequences."}, {"letter": "C", "text": "retained altered methylation of a specific growth gene throughout life."}, {"letter": "D", "text": "had children who were much smaller than normal at adult age."}]'::jsonb WHERE id = '71ea59e3-1dc5-5cbf-b046-d7f64186f079';
UPDATE test_questions SET options = '[{"letter": "A", "text": "Human cooperation is restricted exclusively to immediate genetic family members."}, {"letter": "B", "text": "Humans routinely collaborate on a large scale with individuals who are not genetic relatives."}, {"letter": "C", "text": "Human societies operate without any division of labor or specialized roles."}, {"letter": "D", "text": "Animals use formal legal systems to punish free-riding members of their groups."}]'::jsonb WHERE id = 'aac79a77-b90b-5797-81f9-662b90de8946';
UPDATE test_questions SET options = '[{"letter": "A", "text": "Overall cooperation declines quickly as players turn to selfish strategies."}, {"letter": "B", "text": "Contributions to the common pool remain close to one hundred percent."}, {"letter": "C", "text": "Players voluntarily donate all their personal money to charity."}, {"letter": "D", "text": "Players choose to leave the game rather than interact with strangers."}]'::jsonb WHERE id = 'b33909c5-4d32-5ba9-863c-8ed1f21f2f36';
UPDATE test_questions SET options = '[{"letter": "A", "text": "People who steal from public goods pools are punished twice by the group."}, {"letter": "B", "text": "Individuals who contribute to tasks but avoid the costs of punishing others gain an evolutionary advantage."}, {"letter": "C", "text": "Punishers are rewarded with extra financial resources by government authorities."}, {"letter": "D", "text": "Free-riders are forced to pay double fines when caught violating laws."}]'::jsonb WHERE id = '816cdb60-7bc0-5f3d-979b-c9624b63325f';
UPDATE test_questions SET options = '[{"letter": "A", "text": "causes severe physical distress and pain in the prefrontal cortex."}, {"letter": "B", "text": "activates brain regions associated with pleasure and reward anticipation."}, {"letter": "C", "text": "shuts down the subject''s memory processing systems completely."}, {"letter": "D", "text": "requires slow, complex mathematical calculations about long-term profits."}]'::jsonb WHERE id = 'add3c7d8-0562-532f-a5ed-e6d2665406d2';
UPDATE test_questions SET options = '[{"letter": "A", "text": "participants used money to punish players who made generous contributions."}, {"letter": "B", "text": "punishment was strictly prohibited by cultural religious doctrines."}, {"letter": "C", "text": "high contributors were granted special political titles by other players."}, {"letter": "D", "text": "players refused to accept any financial rewards from successful games."}]'::jsonb WHERE id = '4b1265c8-1e80-5d61-b380-575fefca7c6a';
UPDATE test_questions SET options = '[{"letter": "A", "text": "Spoken language evolved purely to mimic the sounds of nature."}, {"letter": "B", "text": "Language strictly determines human thought and limits what is thinkable."}, {"letter": "C", "text": "All world languages share identical underlying grammatical structures."}, {"letter": "D", "text": "Children learn to think only after they master writing and reading."}]'::jsonb WHERE id = 'a54dc8fc-f260-530d-922f-12423286c530';
UPDATE test_questions SET options = '[{"letter": "A", "text": "follow a predictable and universal evolutionary sequence."}, {"letter": "B", "text": "are assigned randomly with no biological constraints."}, {"letter": "C", "text": "prevent speakers of two-term languages from seeing yellow light."}, {"letter": "D", "text": "are created entirely by commercial trade networks."}]'::jsonb WHERE id = '730f94cc-faed-582a-93c3-0b84caeda3c6';
UPDATE test_questions SET options = '[{"letter": "A", "text": "By relying exclusively on body-relative terms like left and right."}, {"letter": "B", "text": "By using absolute cardinal coordinates such as north and south."}, {"letter": "C", "text": "By comparing all objects to the position of the ocean tide."}, {"letter": "D", "text": "By measuring distances using astronomical constellations."}]'::jsonb WHERE id = 'd992e873-38cf-5813-8279-136e434563a2';
UPDATE test_questions SET options = '[{"letter": "A", "text": "Their performance speeds up dramatically due to cognitive enhancement."}, {"letter": "B", "text": "They lose the ability to see differences between bright colors."}, {"letter": "C", "text": "Relativistic language biases disappear and basic performance returns."}, {"letter": "D", "text": "They are unable to remember any words in their native tongue."}]'::jsonb WHERE id = '62d7c828-def9-5bb4-8a4f-55bfd0d64433';
UPDATE test_questions SET options = '[{"letter": "A", "text": "Voters refuse to participate in elections if there are more than two candidates."}, {"letter": "B", "text": "Individual rational preferences can result in a circular and contradictory group preference."}, {"letter": "C", "text": "Dictatorial leaders always emerge whenever majority voting is used in small committees."}, {"letter": "D", "text": "Sincere voting produces identical outcomes across all historical elections."}]'::jsonb WHERE id = 'ec8e27ff-cea9-5b54-99d2-04911e415949';
UPDATE test_questions SET options = '[{"letter": "A", "text": "Modern voting systems require digital computers to count paper ballots accurately."}, {"letter": "B", "text": "No voting system with three or more options can meet all basic fairness rules at once."}, {"letter": "C", "text": "Dictatorships are more economically productive than democratic governments."}, {"letter": "D", "text": "Most voters make irrational and emotional choices during political campaigns."}]'::jsonb WHERE id = 'a01812df-2ee6-58e2-a67c-6601b1f30000';
UPDATE test_questions SET options = '[{"letter": "A", "text": "how a third candidate can change the final result between the top two contenders."}, {"letter": "B", "text": "why manual paper ballots should never be used in national elections."}, {"letter": "C", "text": "that voters always vote tactically rather than supporting their favorite candidate."}, {"letter": "D", "text": "how electronic voting machines eliminate all forms of electoral bias."}]'::jsonb WHERE id = '98611bb7-9e82-566d-b93d-1a7763a78360';
UPDATE test_questions SET options = '[{"letter": "A", "text": "are completely immune to strategic voting and personal manipulation."}, {"letter": "B", "text": "can be manipulated by voters who choose not to vote sincerely."}, {"letter": "C", "text": "require at least five political parties to maintain democratic stability."}, {"letter": "D", "text": "result in identical winners regardless of what rules are applied."}]'::jsonb WHERE id = '28d762b7-83ce-5814-b940-3de9e0639c2c';
UPDATE test_questions SET options = '[{"letter": "A", "text": "scientific theories are valid only if they increase corporate profits."}, {"letter": "B", "text": "a model is true if its concepts match actual entities in the real world."}, {"letter": "C", "text": "human thoughts are entirely independent of sensory perceptions."}, {"letter": "D", "text": "all physical laws change whenever a new president is elected."}]'::jsonb WHERE id = '3e936960-d3e0-5a5e-aea4-c50ef8cc040f';
UPDATE test_questions SET options = '[{"letter": "A", "text": "must be a perfect physical copy of the universe''s internal mechanisms."}, {"letter": "B", "text": "proves that all other models are permanently useless."}, {"letter": "C", "text": "fits within practical constraints to work without proving it matches absolute reality."}, {"letter": "D", "text": "unlocks supernatural powers inside the human mind."}]'::jsonb WHERE id = 'd6f5e70f-7174-582b-a0be-ff794c0f6073';
UPDATE test_questions SET options = '[{"letter": "A", "text": "Copernicus proved that Ptolemaic calculations were entirely wrong about every eclipse."}, {"letter": "B", "text": "Ptolemy''s geocentric model was never able to predict planetary movements."}, {"letter": "C", "text": "Copernicus introduced a different conceptual framework that was more viable and simpler."}, {"letter": "D", "text": "Religious authorities forced astronomers to use heliocentrism against their will."}]'::jsonb WHERE id = 'd8a6bde2-7469-5069-a460-735d225e6cec';
UPDATE test_questions SET options = '[{"letter": "A", "text": "By arguing that humans can walk through solid walls if they believe in constructivism."}, {"letter": "B", "text": "By showing that conceptual models are strictly constrained when they collide with reality."}, {"letter": "C", "text": "By rejecting all empirical experiments conducted in physics laboratories."}, {"letter": "D", "text": "By claiming that scientific truth is decided entirely by political voting."}]'::jsonb WHERE id = '2bee9c7f-8f40-53bc-9fde-a010f4ebfc35';
UPDATE test_questions SET options = '[{"letter": "A", "text": "Moral choices must follow absolute religious rules without exception."}, {"letter": "B", "text": "Actions should be evaluated entirely by the overall outcomes they produce."}, {"letter": "C", "text": "Human emotions should be ignored completely in personal legal disputes."}, {"letter": "D", "text": "Individuals have a natural duty to prioritize their own financial wealth."}]'::jsonb WHERE id = '1fd7e5ee-a0ba-5564-b575-f10aa589499a';
UPDATE test_questions SET options = '[{"letter": "A", "text": "rapid, evolutionarily ancient emotional brain systems."}, {"letter": "B", "text": "slow mathematical calculations conducted in university classrooms."}, {"letter": "C", "text": "strict legal penalties enforced by national governments."}, {"letter": "D", "text": "reading classical philosophical literature during childhood."}]'::jsonb WHERE id = '6fa10acf-8607-56bf-b535-bcc396a38a86';
UPDATE test_questions SET options = '[{"letter": "A", "text": "they believe that five lives are less valuable than one life."}, {"letter": "B", "text": "the train moves too quickly for the man to block it."}, {"letter": "C", "text": "the situation triggers an immediate, strong emotional alarm in the brain."}, {"letter": "D", "text": "they are afraid of being sued by the railway company."}]'::jsonb WHERE id = '0fd6ebdf-989e-5dd3-9169-bdb775621b8b';
UPDATE test_questions SET options = '[{"letter": "A", "text": "Innate emotional impulses designed to stop physical fighting."}, {"letter": "B", "text": "Deliberate, effortful cost- benefit calculations in the prefrontal cortex."}, {"letter": "C", "text": "Following traditional social customs established by ancient tribes."}, {"letter": "D", "text": "Relying on pre-programmed computer chips to make moral laws."}]'::jsonb WHERE id = '1256deb0-7eed-5396-abff-b6f695f81748';
UPDATE test_questions SET options = '[{"letter": "A", "text": "Utilitarian choices on trolley problems may sometimes reflect a lack of empathy rather than superior rationality."}, {"letter": "B", "text": "Functional MRI scans cannot record any metabolic activity in the human brain."}, {"letter": "C", "text": "Modern philosophers have completely stopped discussing the Trolley Problem."}, {"letter": "D", "text": "Deontological ethics was invented only in the late twentieth century."}]'::jsonb WHERE id = '87cdbb26-8b97-5bb0-9962-8aa32de93e41';
UPDATE test_questions SET options = '[{"letter": "A", "text": "Organisms consciously modify their DNA sequences to survive weather shifts."}, {"letter": "B", "text": "The environment acts as an independent filter that selects random genetic mutations."}, {"letter": "C", "text": "Living creatures possess an internal biological drive to achieve perfection."}, {"letter": "D", "text": "The physical environment changes only when massive asteroids strike the Earth."}]'::jsonb WHERE id = 'a8b7c9ce-7235-5e77-9ce7-ed888c5e2823';
UPDATE test_questions SET options = '[{"letter": "A", "text": "are passive objects that have no physical impact on their surroundings."}, {"letter": "B", "text": "survive only by reproducing through non-sexual cloning methods."}, {"letter": "C", "text": "actively alter their environments and change the selective forces acting on them."}, {"letter": "D", "text": "can adapt to new habitats without using any physiological energy."}]'::jsonb WHERE id = 'f1c98e70-8a69-50fe-ab2a-7ff6da4a6759';
UPDATE test_questions SET options = '[{"letter": "A", "text": "Its dam building creates an aquatic habitat that drives its own physical evolution."}, {"letter": "B", "text": "It survives exclusively by eating fish from deep oceanic waters."}, {"letter": "C", "text": "It stops all other animal species from living near river channels."}, {"letter": "D", "text": "It relies entirely on stone tools to carve deep burrows in mountain rocks."}]'::jsonb WHERE id = 'c3d7a9b9-2bd4-5a21-8c64-fab0e466b483';
UPDATE test_questions SET options = '[{"letter": "A", "text": "why genetic mutations are the only factor that influences animal survival."}, {"letter": "B", "text": "how organisms leave a modified physical environment to future generations."}, {"letter": "C", "text": "that animals without backbones cannot survive in nutrient-rich soils."}, {"letter": "D", "text": "why soil composition remains identical regardless of animal behavior."}]'::jsonb WHERE id = 'b5bcfcd5-121c-569b-b29a-db663489b358';
UPDATE test_questions SET options = '[{"letter": "A", "text": "Beavers do not actually construct wooden dams across river channels."}, {"letter": "B", "text": "Niche- constructing behaviors are simply traits that were originally created by standard natural selection."}, {"letter": "C", "text": "The human ability to digest milk is not related to pastoral dairy farming."}, {"letter": "D", "text": "Genetic mutations play no role in the evolutionary development of animals."}]'::jsonb WHERE id = 'fd0a5c72-58b4-563a-b115-71c093298931';
UPDATE test_questions SET options = '[{"letter": "A", "text": "a chaotic series of political rebellions by younger scientists."}, {"letter": "B", "text": "a steady, linear buildup of objective factual knowledge."}, {"letter": "C", "text": "an unpredictable cycle of religious beliefs replacing earlier theories."}, {"letter": "D", "text": "a process that occurs entirely without mathematical equations."}]'::jsonb WHERE id = '405a7ea3-f430-5aa3-834e-24c717ca19d4';
UPDATE test_questions SET options = '[{"letter": "A", "text": "Constantly trying to disprove and overthrow the dominant paradigm."}, {"letter": "B", "text": "Solving internal puzzles and refining details within the existing paradigm."}, {"letter": "C", "text": "Burning all historical research papers published by previous scientists."}, {"letter": "D", "text": "Banning laboratory instruments that produce unusual measurements."}]'::jsonb WHERE id = '07e1dda4-4497-5dca-8d7b-709e70b045f3';
UPDATE test_questions SET options = '[{"letter": "A", "text": "It changes from an unchangeable property to a velocity-dependent property."}, {"letter": "B", "text": "It is removed entirely from all modern physics textbooks."}, {"letter": "C", "text": "It keeps the exact same mathematical definition in both systems."}, {"letter": "D", "text": "It refers strictly to the number of electrons inside an atomic nucleus."}]'::jsonb WHERE id = '28ae989d-2275-5681-9b1e-9e3fbcddff47';
UPDATE test_questions SET options = '[{"letter": "A", "text": "astronomers always agree on the physical movement of the stars."}, {"letter": "B", "text": "scientific observations are shaped by the observer''s theoretical beliefs."}, {"letter": "C", "text": "ancient telescopes were too weak to measure the speed of the sun."}, {"letter": "D", "text": "visual observations are completely useless in astronomical research."}]'::jsonb WHERE id = '6f67737d-95b9-5348-88ab-76851f5d6f70';
UPDATE test_questions SET options = '[{"letter": "A", "text": "They praised Kuhn for showing that science is identical to artistic fashion."}, {"letter": "B", "text": "They argued that Kuhn reduced scientific transitions to irrational social trends."}, {"letter": "C", "text": "They proved that no scientific paradigms had ever existed in human history."}, {"letter": "D", "text": "They demanded that all university science faculties be closed immediately."}]'::jsonb WHERE id = '12dca96c-7486-5f04-b4bc-4604c665a4ba';
UPDATE test_questions SET options = '[{"letter": "A", "text": "Time perception is controlled entirely by skin temperature."}, {"letter": "B", "text": "The human body has no single sensory organ dedicated to measuring time."}, {"letter": "C", "text": "Human beings cannot estimate intervals that last for more than one second."}, {"letter": "D", "text": "Time is perceived only when an individual is in a deep sleep."}]'::jsonb WHERE id = '87c31d3d-878a-588d-b2eb-2e8f257968ef';
UPDATE test_questions SET options = '[{"letter": "A", "text": "It emits electrical waves to destroy damaged nerve cells."}, {"letter": "B", "text": "It collects and counts the pulses emitted by the pacemaker."}, {"letter": "C", "text": "It blocks all incoming auditory sounds during decision-making."}, {"letter": "D", "text": "It resets the physical heartbeat to a slower baseline rhythm."}]'::jsonb WHERE id = 'eaa07784-6a4b-5759-9525-a20bcc1b539e';
UPDATE test_questions SET options = '[{"letter": "A", "text": "medium spiny neurons in the striatum identifying specific cortical oscillatory patterns."}, {"letter": "B", "text": "a single clock cell located deep within the human ear canal."}, {"letter": "C", "text": "microscopic magnetic minerals floating inside the blood stream."}, {"letter": "D", "text": "the continuous release of adrenaline from the adrenal glands."}]'::jsonb WHERE id = 'a887e810-2231-5772-9753-a101ec982a59';
UPDATE test_questions SET options = '[{"letter": "A", "text": "They make subjects feel that external intervals are longer by speeding up internal rhythms."}, {"letter": "B", "text": "They completely eliminate the human ability to track speech sounds."}, {"letter": "C", "text": "They slow down the firing rate of every cortical brain cell to zero."}, {"letter": "D", "text": "They cause individuals to forget all memories from their childhood."}]'::jsonb WHERE id = '6c0b045e-82ce-5127-a0a9-acbed4587fd7';
UPDATE test_questions SET options = '[{"letter": "A", "text": "The olfactory bulb"}, {"letter": "B", "text": "The cerebellum"}, {"letter": "C", "text": "The stomach nervous system"}, {"letter": "D", "text": "The spinal marrow"}]'::jsonb WHERE id = 'd621cd09-312a-54ba-ab69-cc5d6a6ca1ca';
UPDATE test_questions SET options = '[{"letter": "A", "text": "linguistic meanings change whenever a speaker moves to a new city."}, {"letter": "B", "text": "identical physical brain states must produce identical semantic meanings."}, {"letter": "C", "text": "spoken words have no connection to human neurological brain states."}, {"letter": "D", "text": "dictionary definitions must be approved by national government committees."}]'::jsonb WHERE id = '4f5b69b4-b8b4-5124-9299-af73711e012f';
UPDATE test_questions SET options = '[{"letter": "A", "text": "genetic mutations inherited from parents."}, {"letter": "B", "text": "the social linguistic conventions of a speaker''s community."}, {"letter": "C", "text": "how often an individual exercises during the week."}, {"letter": "D", "text": "the temperature of the medical examination room."}]'::jsonb WHERE id = '1c1c567c-5ada-5a4b-a4aa-f3c030ae24be';
UPDATE test_questions SET options = '[{"letter": "A", "text": "The internal cognitive meaning that remains identical between physical duplicates."}, {"letter": "B", "text": "The real-world chemical formula determined by laboratory scientists."}, {"letter": "C", "text": "The historical origin of Latin words in modern European dictionaries."}, {"letter": "D", "text": "The exact physical weight of the human brain inside the skull."}]'::jsonb WHERE id = '3b969e46-8635-5d94-b316-e936c414531d';
UPDATE test_questions SET options = '[{"letter": "A", "text": "Technologies were banned immediately before any tests could be conducted."}, {"letter": "B", "text": "Suspected activities were allowed until clear scientific proof of harm was established."}, {"letter": "C", "text": "Private companies paid heavy fines before launching any new products."}, {"letter": "D", "text": "Environmental laws were rewritten every time weather patterns changed."}]'::jsonb WHERE id = '5274b554-6cf3-5742-8756-438935002d94';
UPDATE test_questions SET options = '[{"letter": "A", "text": "scientific uncertainty should not be used to delay actions preventing environmental damage."}, {"letter": "B", "text": "all chemical factories must be relocated to uninhabited islands."}, {"letter": "C", "text": "environmental treaties are voluntary and cannot be enforced by law."}, {"letter": "D", "text": "economic development is always more important than protecting wildlife."}]'::jsonb WHERE id = '90d4890e-598d-5b00-85b5-2fdebc2caeef';
UPDATE test_questions SET options = '[{"letter": "A", "text": "Regulatory agencies lack the computing power to process legal paperwork."}, {"letter": "B", "text": "Banning a technology to avoid one risk often introduces new, alternative risks."}, {"letter": "C", "text": "Most citizens refuse to participate in public environmental debates."}, {"letter": "D", "text": "High court judges are not qualified to evaluate scientific experiments."}]'::jsonb WHERE id = '721f9ea6-48f7-5cb2-b2bf-91f5808410b2';
UPDATE test_questions SET options = '[{"letter": "A", "text": "Knightian uncertainty applies only to games of chance like roulette."}, {"letter": "B", "text": "Risk occurs when all probabilities are completely unquantifiable."}, {"letter": "C", "text": "Knightian uncertainty occurs when the exact probabilities of outcomes are unknown."}, {"letter": "D", "text": "Risk can never be calculated using mathematical multiplication."}]'::jsonb WHERE id = 'b7f10392-6a54-5701-9a09-36204957642b';
UPDATE test_questions SET options = '[{"letter": "A", "text": "By ensuring that precaution is applied only to scientifically plausible hazards."}, {"letter": "B", "text": "By allowing private corporations to write their own safety regulations."}, {"letter": "C", "text": "By completely ignoring all worst-case environmental scenarios."}, {"letter": "D", "text": "By replacing human judges with automated artificial intelligence systems."}]'::jsonb WHERE id = '8e393cfa-3e2a-5828-99bd-4ce2879d7cb7';
UPDATE test_questions SET options = '[{"letter": "A", "text": "formal logical deduction and internal symbolic representations."}, {"letter": "B", "text": "biological evolution driven purely by natural selection."}, {"letter": "C", "text": "physical instincts that operate without any cognitive processing."}, {"letter": "D", "text": "the chemical balance of fluids inside the human inner ear."}]'::jsonb WHERE id = 'e2c7d438-8f7e-5522-b78e-961b153bc651';
UPDATE test_questions SET options = '[{"letter": "A", "text": "Robots running out of battery power when climbing steep stairs."}, {"letter": "B", "text": "The challenge of mathematically representing what stays the same after an action."}, {"letter": "C", "text": "The inability of computer screens to display high-resolution color images."}, {"letter": "D", "text": "Mechanical gear wheels breaking under heavy physical loads."}]'::jsonb WHERE id = 'f9e21bb5-f72b-560b-b776-1f4fb976c901';
UPDATE test_questions SET options = '[{"letter": "A", "text": "Frame axioms can only be written in ancient classical languages."}, {"letter": "B", "text": "The number of required non-change statements grows exponentially, causing delays."}, {"letter": "C", "text": "Computers require liquid nitrogen cooling to read frame axioms."}, {"letter": "D", "text": "Frame axioms delete all operating software files from the hard drive."}]'::jsonb WHERE id = '7641da20-d172-50da-b871-80a3d6398136';
UPDATE test_questions SET options = '[{"letter": "A", "text": "building robots that used the physical world directly rather than complex internal maps."}, {"letter": "B", "text": "proving that all robots must be built using expensive gold wiring."}, {"letter": "C", "text": "demonstrating that computers cannot process digital numbers."}, {"letter": "D", "text": "showing that machines must be programmed with billions of frame axioms."}]'::jsonb WHERE id = 'ef760edc-7ceb-5549-8c4f-a6b583354d2c';
UPDATE test_questions SET options = '[{"letter": "A", "text": "distributed across the entire solar system."}, {"letter": "B", "text": "confined strictly within the biological skull and skin of an organism."}, {"letter": "C", "text": "located entirely inside digital computer hardware."}, {"letter": "D", "text": "created by magnetic waves emitted by ocean currents."}]'::jsonb WHERE id = '6107f97b-721e-56e3-a221-a34a2731fd99';
UPDATE test_questions SET options = '[{"letter": "A", "text": "non-biological external tools can function as literal components of the cognitive system."}, {"letter": "B", "text": "humans will soon evolve telepathic powers to read others'' thoughts."}, {"letter": "C", "text": "physical paper notebooks should be banned in public schools."}, {"letter": "D", "text": "the human brain contains no biological neurons or blood vessels."}]'::jsonb WHERE id = '55fe943f-e99e-52be-9585-3a9440959472';
UPDATE test_questions SET options = '[{"letter": "A", "text": "External tools must be made of biological materials to count as cognitive."}, {"letter": "B", "text": "Cognitive status is defined by functional role rather than physical location or material."}, {"letter": "C", "text": "All humans possess identical intelligence scores on standardized tests."}, {"letter": "D", "text": "Machines should never be used to store human telephone numbers."}]'::jsonb WHERE id = '4e3ce86b-b1a6-5613-9cc8-2387d8a40fc1';
UPDATE test_questions SET options = '[{"letter": "A", "text": "It provides a biological heart monitor to measure his blood pressure."}, {"letter": "B", "text": "It performs the same functional memory role as Inga''s biological brain."}, {"letter": "C", "text": "It proves that Alzheimer''s disease can be cured using paper products."}, {"letter": "D", "text": "It prevents Otto from walking into buildings in New York City."}]'::jsonb WHERE id = 'e6520538-2873-5bd5-9adf-d32dfc47c1e9';
UPDATE test_questions SET options = '[{"letter": "A", "text": "Confusing a causal link to an external tool with that tool being a literal part of the mind."}, {"letter": "B", "text": "Proving that stethoscopes are responsible for human brain damage."}, {"letter": "C", "text": "Arguing that human beings cannot write words on paper."}, {"letter": "D", "text": "Claiming that computers have biological intentions."}]'::jsonb WHERE id = '209eb5a0-41c0-535c-97ea-4a0ea0bb1102';

COMMIT;
