-- =====================================================================
-- Migration 0024 — Seed IELTS Listening Mock Tests 11-14
-- Generated by scripts/r2-listening-seed/generate_seed_sql.py — do not
-- hand-edit; re-run the generator instead if the source data changes.
--
-- Model (same as migrations/seed_listening_test_77*.sql):
--   * 1 row in `tests`         -> the mock test (skill='listening')
--   * `test_sections` rows      -> one per question-type block; a single
--                                  IELTS section can have >1 row sharing
--                                  the same merged audio_url
--   * `test_questions`/`test_answers` -> all 40 questions + answer key
--
-- Run: psql "$DATABASE_URL" -f migrations/0024_seed_listening_tests_11_14.sql
-- Idempotent: re-running replaces each test's sections/questions cleanly.
-- =====================================================================

BEGIN;

SET client_encoding = 'UTF8';

-- ---- Mock Test 11 ------------------------------------------------
DO $$
DECLARE
    v_test_id UUID := '11f6fd45-2646-5925-a4ab-ae8ee4972ac3';
    v_section_id UUID;
    v_qid UUID;
BEGIN
    INSERT INTO tests (id, skill, title, description, instructions, duration_seconds, position, is_published)
    VALUES (
        v_test_id,
        'listening',
        'IELTS Listening Mock Test 11',
        'Section 1: enquiring about a local language exchange club. Section 2: orientation at a public sports centre (floor plan labelling). Section 3: university research project on student travel and public transport. Section 4: lecture on forests and the water cycle.',
        'You will hear the recording once. Answer all 40 questions as you listen. Complete the notes and choose the correct letters as instructed in each section.',
        1680,
        11,
        TRUE
    )
    ON CONFLICT (id) DO UPDATE
        SET title = EXCLUDED.title,
            description = EXCLUDED.description,
            instructions = EXCLUDED.instructions,
            duration_seconds = EXCLUDED.duration_seconds,
            position = EXCLUDED.position,
            is_published = EXCLUDED.is_published,
            updated_at = now();

    DELETE FROM test_sections WHERE test_id = v_test_id;

    -- Section 1 — Questions 1-10
    v_section_id := '4d0d8d6f-40aa-57a3-a74d-792d866480bb';
    INSERT INTO test_sections (id, test_id, position, title, instructions, audio_url)
    VALUES (
        v_section_id, v_test_id,
        1, 'Section 1 — Questions 1-10', 'LANGUAGE EXCHANGE CLUB. Complete the notes below. Write ONE WORD AND/OR A NUMBER for each answer.',
        'https://pub-7ae6bc0d9be44caba0b1258ca079ce53.r2.dev/listening-tests/test-11/full.mp3'
    );

    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, max_words)
      VALUES (v_qid, v_section_id, 1, 1, 'text_input', 'Ben wants to practise ____.', 1);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["French"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, max_words)
      VALUES (v_qid, v_section_id, 2, 2, 'text_input', 'The French group meets on ____.', 1);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["Thursday"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, max_words)
      VALUES (v_qid, v_section_id, 3, 3, 'text_input', 'Each session lasts approximately ____ minutes.', 1);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["90"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, max_words)
      VALUES (v_qid, v_section_id, 4, 4, 'text_input', 'There is no formal ____.', 1);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["homework"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, max_words)
      VALUES (v_qid, v_section_id, 5, 5, 'text_input', 'Membership costs ____ pounds for six months.', 1);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["30"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, max_words)
      VALUES (v_qid, v_section_id, 6, 6, 'text_input', 'The group meets at Oak Street Community ____.', 1);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["Centre", "Center"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, max_words)
      VALUES (v_qid, v_section_id, 7, 7, 'text_input', 'The group uses Room ____.', 1);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["Seven", "7"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, max_words)
      VALUES (v_qid, v_section_id, 8, 8, 'text_input', 'The next meeting is on the ____ of November.', 1);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["ninth", "9th"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, max_words)
      VALUES (v_qid, v_section_id, 9, 9, 'text_input', 'Members should register by the ____ of November.', 1);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["second", "2nd"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, max_words)
      VALUES (v_qid, v_section_id, 10, 10, 'text_input', 'The group normally has around ____ people.', 1);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["12", "twelve"]');

    -- Section 2 — Questions 11-15
    v_section_id := '30ed567e-8ffb-5c04-b588-b81af246d8c6';
    INSERT INTO test_sections (id, test_id, position, title, instructions, audio_url)
    VALUES (
        v_section_id, v_test_id,
        2, 'Section 2 — Questions 11-15', 'Complete the notes below. Write ONE WORD AND/OR A NUMBER for each answer.',
        'https://pub-7ae6bc0d9be44caba0b1258ca079ce53.r2.dev/listening-tests/test-11/full.mp3'
    );

    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, max_words)
      VALUES (v_qid, v_section_id, 11, 11, 'text_input', 'The main entrance is at the ____ of the plan.', 1);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["bottom"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, max_words)
      VALUES (v_qid, v_section_id, 12, 12, 'text_input', 'Reception is immediately ____ the entrance.', 1);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["inside"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, max_words)
      VALUES (v_qid, v_section_id, 13, 13, 'text_input', 'The main gym is on the ____ side.', 1);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["left"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, max_words)
      VALUES (v_qid, v_section_id, 14, 14, 'text_input', 'The swimming pool is on the ____ side.', 1);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["right"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, max_words)
      VALUES (v_qid, v_section_id, 15, 15, 'text_input', 'The changing rooms are ____ the gym and pool.', 1);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["between"]');

    -- Section 2 — Questions 16-20 (Floor Plan Labelling)
    v_section_id := '0d2b2243-8f11-5d37-be9f-1c9b660b45a9';
    INSERT INTO test_sections (id, test_id, position, title, instructions, audio_url, image_url)
    VALUES (
        v_section_id, v_test_id,
        2, 'Section 2 — Questions 16-20 (Floor Plan Labelling)', 'Label the plan below. Choose the correct letter, A–H.',
        'https://pub-7ae6bc0d9be44caba0b1258ca079ce53.r2.dev/listening-tests/test-11/full.mp3',
        'https://pub-7ae6bc0d9be44caba0b1258ca079ce53.r2.dev/listening-tests/test-11/section-2-map.jpg'
    );

    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, options)
      VALUES (v_qid, v_section_id, 16, 16, 'map_label', 'Reception', '[{"letter": "A"}, {"letter": "B"}, {"letter": "C"}, {"letter": "D"}, {"letter": "E"}, {"letter": "F"}, {"letter": "G"}, {"letter": "H"}]'::jsonb);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["a"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, options)
      VALUES (v_qid, v_section_id, 17, 17, 'map_label', 'Main Gym', '[{"letter": "A"}, {"letter": "B"}, {"letter": "C"}, {"letter": "D"}, {"letter": "E"}, {"letter": "F"}, {"letter": "G"}, {"letter": "H"}]'::jsonb);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["b"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, options)
      VALUES (v_qid, v_section_id, 18, 18, 'map_label', 'Swimming Pool', '[{"letter": "A"}, {"letter": "B"}, {"letter": "C"}, {"letter": "D"}, {"letter": "E"}, {"letter": "F"}, {"letter": "G"}, {"letter": "H"}]'::jsonb);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["c"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, options)
      VALUES (v_qid, v_section_id, 19, 19, 'map_label', 'Changing Rooms', '[{"letter": "A"}, {"letter": "B"}, {"letter": "C"}, {"letter": "D"}, {"letter": "E"}, {"letter": "F"}, {"letter": "G"}, {"letter": "H"}]'::jsonb);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["d"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, options)
      VALUES (v_qid, v_section_id, 20, 20, 'map_label', 'Fitness Studio', '[{"letter": "A"}, {"letter": "B"}, {"letter": "C"}, {"letter": "D"}, {"letter": "E"}, {"letter": "F"}, {"letter": "G"}, {"letter": "H"}]'::jsonb);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["e"]');

    -- Section 3 — Questions 21-25
    v_section_id := '2d3f9163-cbe0-5bfb-9377-89acaab2433e';
    INSERT INTO test_sections (id, test_id, position, title, instructions, audio_url)
    VALUES (
        v_section_id, v_test_id,
        3, 'Section 3 — Questions 21-25', 'Choose the correct letter, A, B or C.',
        'https://pub-7ae6bc0d9be44caba0b1258ca079ce53.r2.dev/listening-tests/test-11/full.mp3'
    );

    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, options)
      VALUES (v_qid, v_section_id, 21, 21, 'single_choice', 'What is the main focus of the project?', '[{"letter": "A", "text": "How students travel to and from university"}, {"letter": "B", "text": "The cost of university accommodation"}, {"letter": "C", "text": "The design of public transport systems"}]'::jsonb);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["a"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, options)
      VALUES (v_qid, v_section_id, 22, 22, 'single_choice', 'Which students will participate?', '[{"letter": "A", "text": "Students living on campus"}, {"letter": "B", "text": "Undergraduate students living off campus"}, {"letter": "C", "text": "Postgraduate students"}]'::jsonb);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["b"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, options)
      VALUES (v_qid, v_section_id, 23, 23, 'single_choice', 'How many questionnaire responses will they target?', '[{"letter": "A", "text": "200"}, {"letter": "B", "text": "250"}, {"letter": "C", "text": "300"}]'::jsonb);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["b"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, options)
      VALUES (v_qid, v_section_id, 24, 24, 'single_choice', 'How many interviews will they conduct?', '[{"letter": "A", "text": "15"}, {"letter": "B", "text": "20"}, {"letter": "C", "text": "25"}]'::jsonb);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["b"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, options)
      VALUES (v_qid, v_section_id, 25, 25, 'single_choice', 'How long will the survey remain open?', '[{"letter": "A", "text": "2 weeks"}, {"letter": "B", "text": "3 weeks"}, {"letter": "C", "text": "4 weeks"}]'::jsonb);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["b"]');

    -- Section 3 — Questions 26-30
    v_section_id := '9451bc4c-bbd2-5053-ae1a-8c663cb3013e';
    INSERT INTO test_sections (id, test_id, position, title, instructions, audio_url)
    VALUES (
        v_section_id, v_test_id,
        3, 'Section 3 — Questions 26-30', 'Who will be responsible for each task? Choose the correct letter, A, B or C.',
        'https://pub-7ae6bc0d9be44caba0b1258ca079ce53.r2.dev/listening-tests/test-11/full.mp3'
    );

    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, options)
      VALUES (v_qid, v_section_id, 26, 26, 'matching', 'Designing the questionnaire', '[{"letter": "A", "text": "Maya"}, {"letter": "B", "text": "Daniel"}, {"letter": "C", "text": "Both students"}]'::jsonb);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["a"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, options)
      VALUES (v_qid, v_section_id, 27, 27, 'matching', 'Organising interviews', '[{"letter": "A", "text": "Maya"}, {"letter": "B", "text": "Daniel"}, {"letter": "C", "text": "Both students"}]'::jsonb);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["b"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, options)
      VALUES (v_qid, v_section_id, 28, 28, 'matching', 'Recruiting participants', '[{"letter": "A", "text": "Maya"}, {"letter": "B", "text": "Daniel"}, {"letter": "C", "text": "Both students"}]'::jsonb);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["c"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, options)
      VALUES (v_qid, v_section_id, 29, 29, 'matching', 'Statistical analysis', '[{"letter": "A", "text": "Maya"}, {"letter": "B", "text": "Daniel"}, {"letter": "C", "text": "Both students"}]'::jsonb);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["a"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, options)
      VALUES (v_qid, v_section_id, 30, 30, 'matching', 'Writing the final recommendations', '[{"letter": "A", "text": "Maya"}, {"letter": "B", "text": "Daniel"}, {"letter": "C", "text": "Both students"}]'::jsonb);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["c"]');

    -- Section 4 — Questions 31-40
    v_section_id := '44babd13-9960-582a-bb43-e20734efdea0';
    INSERT INTO test_sections (id, test_id, position, title, instructions, audio_url)
    VALUES (
        v_section_id, v_test_id,
        4, 'Section 4 — Questions 31-40', 'Complete the notes below. Write NO MORE THAN TWO WORDS for each answer.',
        'https://pub-7ae6bc0d9be44caba0b1258ca079ce53.r2.dev/listening-tests/test-11/full.mp3'
    );

    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, max_words)
      VALUES (v_qid, v_section_id, 31, 31, 'text_input', 'The water cycle describes the movement of water between the atmosphere, land and bodies of ____.', 2);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["water"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, max_words)
      VALUES (v_qid, v_section_id, 32, 32, 'text_input', 'Plants release water vapour through tiny openings in their ____.', 2);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["leaves"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, max_words)
      VALUES (v_qid, v_section_id, 33, 33, 'text_input', 'This process is known as ____.', 2);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["transpiration"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, max_words)
      VALUES (v_qid, v_section_id, 34, 34, 'text_input', 'Trees can return water vapour to the ____.', 2);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["atmosphere"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, max_words)
      VALUES (v_qid, v_section_id, 35, 35, 'text_input', 'Leaves and branches can ____ some rainfall.', 2);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["intercept"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, max_words)
      VALUES (v_qid, v_section_id, 36, 36, 'text_input', 'Forest soils can absorb and ____ water.', 2);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["store"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, max_words)
      VALUES (v_qid, v_section_id, 37, 37, 'text_input', 'Tree roots can increase water ____ into the soil.', 2);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["infiltration"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, max_words)
      VALUES (v_qid, v_section_id, 38, 38, 'text_input', 'Forests can slow the movement of water towards ____.', 2);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["streams"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, max_words)
      VALUES (v_qid, v_section_id, 39, 39, 'text_input', 'Removing forests can increase soil ____.', 2);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["erosion"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, max_words)
      VALUES (v_qid, v_section_id, 40, 40, 'text_input', 'Planting trees in areas where forests were removed is called ____.', 2);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["reforestation"]');

END $$;

-- ---- Mock Test 12 ------------------------------------------------
DO $$
DECLARE
    v_test_id UUID := '362791c6-a3a0-5b1c-8fde-ccb75c7d5120';
    v_section_id UUID;
    v_qid UUID;
BEGIN
    INSERT INTO tests (id, skill, title, description, instructions, duration_seconds, position, is_published)
    VALUES (
        v_test_id,
        'listening',
        'IELTS Listening Mock Test 12',
        'Section 1: booking a room at a community centre. Section 2: orientation at a public library (building map labelling). Section 3: university research project on sleep and academic performance. Section 4: lecture on how coral reefs support marine ecosystems.',
        'You will hear the recording once. Answer all 40 questions as you listen. Complete the notes and choose the correct letters as instructed in each section.',
        1680,
        12,
        TRUE
    )
    ON CONFLICT (id) DO UPDATE
        SET title = EXCLUDED.title,
            description = EXCLUDED.description,
            instructions = EXCLUDED.instructions,
            duration_seconds = EXCLUDED.duration_seconds,
            position = EXCLUDED.position,
            is_published = EXCLUDED.is_published,
            updated_at = now();

    DELETE FROM test_sections WHERE test_id = v_test_id;

    -- Section 1 — Questions 1-10
    v_section_id := '01bf0c05-1ff9-5b30-a1be-2596b99b1ef4';
    INSERT INTO test_sections (id, test_id, position, title, instructions, audio_url)
    VALUES (
        v_section_id, v_test_id,
        1, 'Section 1 — Questions 1-10', 'ROOM BOOKING. Complete the notes below. Write ONE WORD AND/OR A NUMBER for each answer.',
        'https://pub-7ae6bc0d9be44caba0b1258ca079ce53.r2.dev/listening-tests/test-12/full.mp3'
    );

    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, max_words)
      VALUES (v_qid, v_section_id, 1, 1, 'text_input', 'Ethan expects approximately ____ people.', 1);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["30"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, max_words)
      VALUES (v_qid, v_section_id, 2, 2, 'text_input', 'He wants to hire the ____ Room.', 1);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["Willow"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, max_words)
      VALUES (v_qid, v_section_id, 3, 3, 'text_input', 'The room can accommodate up to ____ people seated.', 1);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["40"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, max_words)
      VALUES (v_qid, v_section_id, 4, 4, 'text_input', 'The booking is for Saturday the ____ of December.', 1);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["14th", "fourteenth"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, max_words)
      VALUES (v_qid, v_section_id, 5, 5, 'text_input', 'Ethan plans to start the party at ____ o''clock.', 1);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["2", "two"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, max_words)
      VALUES (v_qid, v_section_id, 6, 6, 'text_input', 'Room hire costs ____ pounds.', 1);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["65"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, max_words)
      VALUES (v_qid, v_section_id, 7, 7, 'text_input', 'A small ____ is available next to the room.', 1);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["kitchen"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, max_words)
      VALUES (v_qid, v_section_id, 8, 8, 'text_input', 'The booking requires a ____-pound deposit.', 1);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["50"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, max_words)
      VALUES (v_qid, v_section_id, 9, 9, 'text_input', 'The remaining payment is due on the ____.', 1);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["day"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, max_words)
      VALUES (v_qid, v_section_id, 10, 10, 'text_input', 'The public car park is behind the ____.', 1);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["centre", "center"]');

    -- Section 2 — Questions 11-15
    v_section_id := '7f46ba9f-ad24-5c49-94b0-c5b05cd29b09';
    INSERT INTO test_sections (id, test_id, position, title, instructions, audio_url)
    VALUES (
        v_section_id, v_test_id,
        2, 'Section 2 — Questions 11-15', 'Complete the notes below. Write ONE WORD AND/OR A NUMBER for each answer.',
        'https://pub-7ae6bc0d9be44caba0b1258ca079ce53.r2.dev/listening-tests/test-12/full.mp3'
    );

    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, max_words)
      VALUES (v_qid, v_section_id, 11, 11, 'text_input', 'The main entrance is at the ____ of the plan.', 1);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["bottom"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, max_words)
      VALUES (v_qid, v_section_id, 12, 12, 'text_input', 'The reception desk is immediately ____ the entrance.', 1);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["inside"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, max_words)
      VALUES (v_qid, v_section_id, 13, 13, 'text_input', 'The children''s library is on the ____ side.', 1);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["left"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, max_words)
      VALUES (v_qid, v_section_id, 14, 14, 'text_input', 'The computer area is on the ____ side.', 1);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["right"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, max_words)
      VALUES (v_qid, v_section_id, 15, 15, 'text_input', 'The reading room is in the ____ of the library.', 1);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["centre", "center"]');

    -- Section 2 — Questions 16-20 (Building Map Labelling)
    v_section_id := '2fc7502c-a18a-5c17-b2e1-b549a765eb0d';
    INSERT INTO test_sections (id, test_id, position, title, instructions, audio_url, image_url)
    VALUES (
        v_section_id, v_test_id,
        2, 'Section 2 — Questions 16-20 (Building Map Labelling)', 'Label the plan below. Choose the correct letter, A–H.',
        'https://pub-7ae6bc0d9be44caba0b1258ca079ce53.r2.dev/listening-tests/test-12/full.mp3',
        'https://pub-7ae6bc0d9be44caba0b1258ca079ce53.r2.dev/listening-tests/test-12/section-2-map.jpg'
    );

    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, options)
      VALUES (v_qid, v_section_id, 16, 16, 'map_label', 'Reception Desk', '[{"letter": "A"}, {"letter": "B"}, {"letter": "C"}, {"letter": "D"}, {"letter": "E"}, {"letter": "F"}, {"letter": "G"}, {"letter": "H"}]'::jsonb);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["a"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, options)
      VALUES (v_qid, v_section_id, 17, 17, 'map_label', 'Children''s Library', '[{"letter": "A"}, {"letter": "B"}, {"letter": "C"}, {"letter": "D"}, {"letter": "E"}, {"letter": "F"}, {"letter": "G"}, {"letter": "H"}]'::jsonb);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["b"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, options)
      VALUES (v_qid, v_section_id, 18, 18, 'map_label', 'Computer Area', '[{"letter": "A"}, {"letter": "B"}, {"letter": "C"}, {"letter": "D"}, {"letter": "E"}, {"letter": "F"}, {"letter": "G"}, {"letter": "H"}]'::jsonb);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["c"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, options)
      VALUES (v_qid, v_section_id, 19, 19, 'map_label', 'Reading Room', '[{"letter": "A"}, {"letter": "B"}, {"letter": "C"}, {"letter": "D"}, {"letter": "E"}, {"letter": "F"}, {"letter": "G"}, {"letter": "H"}]'::jsonb);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["d"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, options)
      VALUES (v_qid, v_section_id, 20, 20, 'map_label', 'Study Room', '[{"letter": "A"}, {"letter": "B"}, {"letter": "C"}, {"letter": "D"}, {"letter": "E"}, {"letter": "F"}, {"letter": "G"}, {"letter": "H"}]'::jsonb);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["e"]');

    -- Section 3 — Questions 21-25
    v_section_id := '0d564bb7-3758-5343-a237-43007f4ef835';
    INSERT INTO test_sections (id, test_id, position, title, instructions, audio_url)
    VALUES (
        v_section_id, v_test_id,
        3, 'Section 3 — Questions 21-25', 'Choose the correct letter, A, B or C.',
        'https://pub-7ae6bc0d9be44caba0b1258ca079ce53.r2.dev/listening-tests/test-12/full.mp3'
    );

    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, options)
      VALUES (v_qid, v_section_id, 21, 21, 'single_choice', 'What is the main focus of the project?', '[{"letter": "A", "text": "The relationship between sleep and academic performance"}, {"letter": "B", "text": "The effect of exercise on university students"}, {"letter": "C", "text": "The cost of university accommodation"}]'::jsonb);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["a"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, options)
      VALUES (v_qid, v_section_id, 22, 22, 'single_choice', 'Which students will participate?', '[{"letter": "A", "text": "Final-year students"}, {"letter": "B", "text": "First-year students"}, {"letter": "C", "text": "Postgraduate students"}]'::jsonb);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["b"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, options)
      VALUES (v_qid, v_section_id, 23, 23, 'single_choice', 'How many questionnaire responses will they target?', '[{"letter": "A", "text": "200"}, {"letter": "B", "text": "240"}, {"letter": "C", "text": "300"}]'::jsonb);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["b"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, options)
      VALUES (v_qid, v_section_id, 24, 24, 'single_choice', 'How many students will keep a sleep diary?', '[{"letter": "A", "text": "20"}, {"letter": "B", "text": "30"}, {"letter": "C", "text": "40"}]'::jsonb);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["b"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, options)
      VALUES (v_qid, v_section_id, 25, 25, 'single_choice', 'How long will the diary period last?', '[{"letter": "A", "text": "5 days"}, {"letter": "B", "text": "7 days"}, {"letter": "C", "text": "14 days"}]'::jsonb);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["b"]');

    -- Section 3 — Questions 26-30
    v_section_id := '3010d18d-8733-55f8-9070-f0f4ec724a34';
    INSERT INTO test_sections (id, test_id, position, title, instructions, audio_url)
    VALUES (
        v_section_id, v_test_id,
        3, 'Section 3 — Questions 26-30', 'Who will be responsible for each task? Choose the correct letter, A, B or C.',
        'https://pub-7ae6bc0d9be44caba0b1258ca079ce53.r2.dev/listening-tests/test-12/full.mp3'
    );

    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, options)
      VALUES (v_qid, v_section_id, 26, 26, 'matching', 'Designing the questionnaire', '[{"letter": "A", "text": "Emma"}, {"letter": "B", "text": "Lucas"}, {"letter": "C", "text": "Both students"}]'::jsonb);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["a"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, options)
      VALUES (v_qid, v_section_id, 27, 27, 'matching', 'Organising the sleep diaries', '[{"letter": "A", "text": "Emma"}, {"letter": "B", "text": "Lucas"}, {"letter": "C", "text": "Both students"}]'::jsonb);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["b"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, options)
      VALUES (v_qid, v_section_id, 28, 28, 'matching', 'Recruiting participants', '[{"letter": "A", "text": "Emma"}, {"letter": "B", "text": "Lucas"}, {"letter": "C", "text": "Both students"}]'::jsonb);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["c"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, options)
      VALUES (v_qid, v_section_id, 29, 29, 'matching', 'Entering questionnaire data', '[{"letter": "A", "text": "Emma"}, {"letter": "B", "text": "Lucas"}, {"letter": "C", "text": "Both students"}]'::jsonb);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["a"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, options)
      VALUES (v_qid, v_section_id, 30, 30, 'matching', 'Writing the final recommendations', '[{"letter": "A", "text": "Emma"}, {"letter": "B", "text": "Lucas"}, {"letter": "C", "text": "Both students"}]'::jsonb);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["c"]');

    -- Section 4 — Questions 31-40
    v_section_id := '766be970-f557-560d-a6c2-30a4aeedcd39';
    INSERT INTO test_sections (id, test_id, position, title, instructions, audio_url)
    VALUES (
        v_section_id, v_test_id,
        4, 'Section 4 — Questions 31-40', 'Complete the notes below. Write NO MORE THAN TWO WORDS for each answer.',
        'https://pub-7ae6bc0d9be44caba0b1258ca079ce53.r2.dev/listening-tests/test-12/full.mp3'
    );

    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, max_words)
      VALUES (v_qid, v_section_id, 31, 31, 'text_input', 'Coral reefs support a large variety of ____ life.', 2);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["marine"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, max_words)
      VALUES (v_qid, v_section_id, 32, 32, 'text_input', 'Microscopic organisms living within coral tissues are called ____.', 2);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["algae"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, max_words)
      VALUES (v_qid, v_section_id, 33, 33, 'text_input', 'These organisms produce energy through ____.', 2);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["photosynthesis"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, max_words)
      VALUES (v_qid, v_section_id, 34, 34, 'text_input', 'Reef-building corals generally require clear, ____ water.', 2);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["shallow"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, max_words)
      VALUES (v_qid, v_section_id, 35, 35, 'text_input', 'Fish can use reefs for shelter and ____.', 2);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["feeding"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, max_words)
      VALUES (v_qid, v_section_id, 36, 36, 'text_input', 'Healthy reefs can support ____ by providing breeding areas for marine species.', 2);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["fisheries"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, max_words)
      VALUES (v_qid, v_section_id, 37, 37, 'text_input', 'Reef structures can reduce the energy of ____ before they reach the shore.', 2);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["waves"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, max_words)
      VALUES (v_qid, v_section_id, 38, 38, 'text_input', 'Coral bleaching can occur when corals experience prolonged ____ stress.', 2);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["heat"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, max_words)
      VALUES (v_qid, v_section_id, 39, 39, 'text_input', 'Increasing carbon dioxide in seawater contributes to ocean ____.', 2);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["acidification"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, max_words)
      VALUES (v_qid, v_section_id, 40, 40, 'text_input', 'One method of protecting reefs is establishing marine ____ areas.', 2);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["protected"]');

END $$;

-- ---- Mock Test 13 ------------------------------------------------
DO $$
DECLARE
    v_test_id UUID := 'b29ed569-7e84-5b81-9184-f23b4e16cce1';
    v_section_id UUID;
    v_qid UUID;
BEGIN
    INSERT INTO tests (id, skill, title, description, instructions, duration_seconds, position, is_published)
    VALUES (
        v_test_id,
        'listening',
        'IELTS Listening Mock Test 13',
        'Section 1: enquiring about a local cooking course. Section 2: orientation at a community health centre (floor plan labelling). Section 3: university research project on student use of green transport. Section 4: lecture on how rivers shape landscapes.',
        'You will hear the recording once. Answer all 40 questions as you listen. Complete the notes and choose the correct letters as instructed in each section.',
        1680,
        13,
        TRUE
    )
    ON CONFLICT (id) DO UPDATE
        SET title = EXCLUDED.title,
            description = EXCLUDED.description,
            instructions = EXCLUDED.instructions,
            duration_seconds = EXCLUDED.duration_seconds,
            position = EXCLUDED.position,
            is_published = EXCLUDED.is_published,
            updated_at = now();

    DELETE FROM test_sections WHERE test_id = v_test_id;

    -- Section 1 — Questions 1-10
    v_section_id := 'ef2b64e2-f1ff-5bee-a69a-4d1146117489';
    INSERT INTO test_sections (id, test_id, position, title, instructions, audio_url)
    VALUES (
        v_section_id, v_test_id,
        1, 'Section 1 — Questions 1-10', 'BEGINNERS'' COOKING COURSE. Complete the notes below. Write ONE WORD AND/OR A NUMBER for each answer.',
        'https://pub-7ae6bc0d9be44caba0b1258ca079ce53.r2.dev/listening-tests/test-13/full.mp3'
    );

    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, max_words)
      VALUES (v_qid, v_section_id, 1, 1, 'text_input', 'Michael wants to improve his cooking of vegetables and simple ____ dishes.', 1);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["meat"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, max_words)
      VALUES (v_qid, v_section_id, 2, 2, 'text_input', 'The course includes basic sauces, knife skills and meal ____.', 1);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["planning"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, max_words)
      VALUES (v_qid, v_section_id, 3, 3, 'text_input', 'The course lasts ____ weeks.', 1);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["6", "six"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, max_words)
      VALUES (v_qid, v_section_id, 4, 4, 'text_input', 'Classes are held on ____ evenings.', 1);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["Wednesday"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, max_words)
      VALUES (v_qid, v_section_id, 5, 5, 'text_input', 'The course costs ____ pounds.', 1);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["95"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, max_words)
      VALUES (v_qid, v_section_id, 6, 6, 'text_input', 'Classes take place at the Riverside Community ____.', 1);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["Kitchen"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, max_words)
      VALUES (v_qid, v_section_id, 7, 7, 'text_input', 'The class is held in Kitchen ____.', 1);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["Three", "3"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, max_words)
      VALUES (v_qid, v_section_id, 8, 8, 'text_input', 'The kitchen is on the ____ floor.', 1);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["ground"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, max_words)
      VALUES (v_qid, v_section_id, 9, 9, 'text_input', 'The next course begins on the ____ of October.', 1);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["seventh", "7th"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, max_words)
      VALUES (v_qid, v_section_id, 10, 10, 'text_input', 'The tutor is Laura ____.', 1);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["Bennett"]');

    -- Section 2 — Questions 11-15
    v_section_id := '569828d9-9010-5cb8-8d58-ea8c87be843c';
    INSERT INTO test_sections (id, test_id, position, title, instructions, audio_url)
    VALUES (
        v_section_id, v_test_id,
        2, 'Section 2 — Questions 11-15', 'Complete the notes below. Write ONE WORD AND/OR A NUMBER for each answer.',
        'https://pub-7ae6bc0d9be44caba0b1258ca079ce53.r2.dev/listening-tests/test-13/full.mp3'
    );

    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, max_words)
      VALUES (v_qid, v_section_id, 11, 11, 'text_input', 'The main entrance is at the ____ of the plan.', 1);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["bottom"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, max_words)
      VALUES (v_qid, v_section_id, 12, 12, 'text_input', 'Reception is immediately ____ the entrance.', 1);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["inside"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, max_words)
      VALUES (v_qid, v_section_id, 13, 13, 'text_input', 'The waiting area is in the ____ of the building.', 1);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["centre", "center"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, max_words)
      VALUES (v_qid, v_section_id, 14, 14, 'text_input', 'Consultation Room One is on the ____.', 1);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["left"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, max_words)
      VALUES (v_qid, v_section_id, 15, 15, 'text_input', 'Consultation Room Two is on the ____.', 1);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["right"]');

    -- Section 2 — Questions 16-20 (Floor Plan Labelling)
    v_section_id := 'ef53ec3c-52fc-531a-83df-5d1cb86e9934';
    INSERT INTO test_sections (id, test_id, position, title, instructions, audio_url, image_url)
    VALUES (
        v_section_id, v_test_id,
        2, 'Section 2 — Questions 16-20 (Floor Plan Labelling)', 'Label the plan below. Choose the correct letter, A–H.',
        'https://pub-7ae6bc0d9be44caba0b1258ca079ce53.r2.dev/listening-tests/test-13/full.mp3',
        'https://pub-7ae6bc0d9be44caba0b1258ca079ce53.r2.dev/listening-tests/test-13/section-2-map.jpg'
    );

    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, options)
      VALUES (v_qid, v_section_id, 16, 16, 'map_label', 'Reception', '[{"letter": "A"}, {"letter": "B"}, {"letter": "C"}, {"letter": "D"}, {"letter": "E"}, {"letter": "F"}, {"letter": "G"}, {"letter": "H"}]'::jsonb);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["a"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, options)
      VALUES (v_qid, v_section_id, 17, 17, 'map_label', 'Waiting Area', '[{"letter": "A"}, {"letter": "B"}, {"letter": "C"}, {"letter": "D"}, {"letter": "E"}, {"letter": "F"}, {"letter": "G"}, {"letter": "H"}]'::jsonb);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["b"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, options)
      VALUES (v_qid, v_section_id, 18, 18, 'map_label', 'Consultation Room 1', '[{"letter": "A"}, {"letter": "B"}, {"letter": "C"}, {"letter": "D"}, {"letter": "E"}, {"letter": "F"}, {"letter": "G"}, {"letter": "H"}]'::jsonb);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["c"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, options)
      VALUES (v_qid, v_section_id, 19, 19, 'map_label', 'Consultation Room 2', '[{"letter": "A"}, {"letter": "B"}, {"letter": "C"}, {"letter": "D"}, {"letter": "E"}, {"letter": "F"}, {"letter": "G"}, {"letter": "H"}]'::jsonb);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["d"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, options)
      VALUES (v_qid, v_section_id, 20, 20, 'map_label', 'Physiotherapy Room', '[{"letter": "A"}, {"letter": "B"}, {"letter": "C"}, {"letter": "D"}, {"letter": "E"}, {"letter": "F"}, {"letter": "G"}, {"letter": "H"}]'::jsonb);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["e"]');

    -- Section 3 — Questions 21-25
    v_section_id := '4db0dbae-8c8e-5f17-be77-a7a8a59bb3d0';
    INSERT INTO test_sections (id, test_id, position, title, instructions, audio_url)
    VALUES (
        v_section_id, v_test_id,
        3, 'Section 3 — Questions 21-25', 'Choose the correct letter, A, B or C.',
        'https://pub-7ae6bc0d9be44caba0b1258ca079ce53.r2.dev/listening-tests/test-13/full.mp3'
    );

    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, options)
      VALUES (v_qid, v_section_id, 21, 21, 'single_choice', 'What is the main focus of the project?', '[{"letter": "A", "text": "Why students choose different forms of transport"}, {"letter": "B", "text": "The cost of building cycle paths"}, {"letter": "C", "text": "Traffic levels in the city centre"}]'::jsonb);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["a"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, options)
      VALUES (v_qid, v_section_id, 22, 22, 'single_choice', 'Which students will participate?', '[{"letter": "A", "text": "Postgraduate students"}, {"letter": "B", "text": "Undergraduate students living within ten kilometres of campus"}, {"letter": "C", "text": "Students living on campus"}]'::jsonb);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["b"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, options)
      VALUES (v_qid, v_section_id, 23, 23, 'single_choice', 'How many questionnaire responses will they target?', '[{"letter": "A", "text": "240"}, {"letter": "B", "text": "280"}, {"letter": "C", "text": "320"}]'::jsonb);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["b"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, options)
      VALUES (v_qid, v_section_id, 24, 24, 'single_choice', 'How many interviews will they conduct?', '[{"letter": "A", "text": "20"}, {"letter": "B", "text": "24"}, {"letter": "C", "text": "30"}]'::jsonb);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["b"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, options)
      VALUES (v_qid, v_section_id, 25, 25, 'single_choice', 'How long will the questionnaire remain open?', '[{"letter": "A", "text": "1 week"}, {"letter": "B", "text": "2 weeks"}, {"letter": "C", "text": "3 weeks"}]'::jsonb);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["b"]');

    -- Section 3 — Questions 26-30
    v_section_id := 'f5dd715d-9b83-5c3b-9fcc-4a18c3d97d40';
    INSERT INTO test_sections (id, test_id, position, title, instructions, audio_url)
    VALUES (
        v_section_id, v_test_id,
        3, 'Section 3 — Questions 26-30', 'Who will be responsible for each task? Choose the correct letter, A, B or C.',
        'https://pub-7ae6bc0d9be44caba0b1258ca079ce53.r2.dev/listening-tests/test-13/full.mp3'
    );

    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, options)
      VALUES (v_qid, v_section_id, 26, 26, 'matching', 'Designing the questionnaire', '[{"letter": "A", "text": "Anna"}, {"letter": "B", "text": "Ryan"}, {"letter": "C", "text": "Both students"}]'::jsonb);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["a"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, options)
      VALUES (v_qid, v_section_id, 27, 27, 'matching', 'Organising interviews', '[{"letter": "A", "text": "Anna"}, {"letter": "B", "text": "Ryan"}, {"letter": "C", "text": "Both students"}]'::jsonb);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["b"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, options)
      VALUES (v_qid, v_section_id, 28, 28, 'matching', 'Recruiting participants', '[{"letter": "A", "text": "Anna"}, {"letter": "B", "text": "Ryan"}, {"letter": "C", "text": "Both students"}]'::jsonb);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["c"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, options)
      VALUES (v_qid, v_section_id, 29, 29, 'matching', 'Statistical analysis', '[{"letter": "A", "text": "Anna"}, {"letter": "B", "text": "Ryan"}, {"letter": "C", "text": "Both students"}]'::jsonb);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["a"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, options)
      VALUES (v_qid, v_section_id, 30, 30, 'matching', 'Writing the final recommendations', '[{"letter": "A", "text": "Anna"}, {"letter": "B", "text": "Ryan"}, {"letter": "C", "text": "Both students"}]'::jsonb);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["c"]');

    -- Section 4 — Questions 31-40
    v_section_id := '0401bce6-af04-5377-bef2-460a1ad294c2';
    INSERT INTO test_sections (id, test_id, position, title, instructions, audio_url)
    VALUES (
        v_section_id, v_test_id,
        4, 'Section 4 — Questions 31-40', 'Complete the notes below. Write NO MORE THAN TWO WORDS for each answer.',
        'https://pub-7ae6bc0d9be44caba0b1258ca079ce53.r2.dev/listening-tests/test-13/full.mp3'
    );

    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, max_words)
      VALUES (v_qid, v_section_id, 31, 31, 'text_input', 'Three important river processes are erosion, transportation and ____.', 2);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["deposition"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, max_words)
      VALUES (v_qid, v_section_id, 32, 32, 'text_input', 'Erosion is the removal of material from the ____.', 2);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["land"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, max_words)
      VALUES (v_qid, v_section_id, 33, 33, 'text_input', 'Fast-moving water can transport more ____.', 2);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["sediment"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, max_words)
      VALUES (v_qid, v_section_id, 34, 34, 'text_input', 'Smaller sediment particles can remain ____ in the water.', 2);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["suspended"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, max_words)
      VALUES (v_qid, v_section_id, 35, 35, 'text_input', 'When a river loses energy, sediment may be ____.', 2);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["deposited"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, max_words)
      VALUES (v_qid, v_section_id, 36, 36, 'text_input', 'Rivers in their upper course often flow through ____ terrain.', 2);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["steeper"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, max_words)
      VALUES (v_qid, v_section_id, 37, 37, 'text_input', 'Wider river bends are called ____.', 2);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["meanders"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, max_words)
      VALUES (v_qid, v_section_id, 38, 38, 'text_input', 'Erosion tends to be stronger on the ____ of a meander.', 2);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["outside"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, max_words)
      VALUES (v_qid, v_section_id, 39, 39, 'text_input', 'Repeated flooding can contribute to the development of ____.', 2);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["floodplains"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, max_words)
      VALUES (v_qid, v_section_id, 40, 40, 'text_input', 'Modern river management increasingly considers the entire river ____.', 2);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["system"]');

END $$;

-- ---- Mock Test 14 ------------------------------------------------
DO $$
DECLARE
    v_test_id UUID := '7715a52e-3c5a-5cc0-b9f0-6b305bcd55ae';
    v_section_id UUID;
    v_qid UUID;
BEGIN
    INSERT INTO tests (id, skill, title, description, instructions, duration_seconds, position, is_published)
    VALUES (
        v_test_id,
        'listening',
        'IELTS Listening Mock Test 14',
        'Section 1: joining a local gardening club. Section 2: orientation at a community arts centre (building map labelling). Section 3: university research project on food waste among students. Section 4: lecture on the role of wetlands in the environment.',
        'You will hear the recording once. Answer all 40 questions as you listen. Complete the notes and choose the correct letters as instructed in each section.',
        1680,
        14,
        TRUE
    )
    ON CONFLICT (id) DO UPDATE
        SET title = EXCLUDED.title,
            description = EXCLUDED.description,
            instructions = EXCLUDED.instructions,
            duration_seconds = EXCLUDED.duration_seconds,
            position = EXCLUDED.position,
            is_published = EXCLUDED.is_published,
            updated_at = now();

    DELETE FROM test_sections WHERE test_id = v_test_id;

    -- Section 1 — Questions 1-10
    v_section_id := '47b93578-25bd-58b4-abad-20af47f34da0';
    INSERT INTO test_sections (id, test_id, position, title, instructions, audio_url)
    VALUES (
        v_section_id, v_test_id,
        1, 'Section 1 — Questions 1-10', 'BEGINNER GARDENING PROGRAMME. Complete the notes below. Write ONE WORD AND/OR A NUMBER for each answer.',
        'https://pub-7ae6bc0d9be44caba0b1258ca079ce53.r2.dev/listening-tests/test-14/full.mp3'
    );

    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, max_words)
      VALUES (v_qid, v_section_id, 1, 1, 'text_input', 'Oliver is mainly interested in growing ____.', 1);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["vegetables"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, max_words)
      VALUES (v_qid, v_section_id, 2, 2, 'text_input', 'The programme lasts ____ weeks.', 1);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["4", "four"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, max_words)
      VALUES (v_qid, v_section_id, 3, 3, 'text_input', 'Sessions take place on ____ mornings.', 1);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["Saturday"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, max_words)
      VALUES (v_qid, v_section_id, 4, 4, 'text_input', 'Each session starts at ____.', 1);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["9:30", "9.30"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, max_words)
      VALUES (v_qid, v_section_id, 5, 5, 'text_input', 'The programme costs ____ pounds.', 1);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["40"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, max_words)
      VALUES (v_qid, v_section_id, 6, 6, 'text_input', 'Sessions are held at the Riverside Allotment ____.', 1);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["Gardens"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, max_words)
      VALUES (v_qid, v_section_id, 7, 7, 'text_input', 'The group meets in a small ____.', 1);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["greenhouse"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, max_words)
      VALUES (v_qid, v_section_id, 8, 8, 'text_input', 'The next programme begins on the ____ of April.', 1);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["twelfth", "12th"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, max_words)
      VALUES (v_qid, v_section_id, 9, 9, 'text_input', 'Registration closes on the ____ of March.', 1);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["twenty-ninth", "29th"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, max_words)
      VALUES (v_qid, v_section_id, 10, 10, 'text_input', 'There are ____ places available.', 1);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["16", "sixteen"]');

    -- Section 2 — Questions 11-15
    v_section_id := '9ea1abdc-b13b-54da-a665-e43b9234a737';
    INSERT INTO test_sections (id, test_id, position, title, instructions, audio_url)
    VALUES (
        v_section_id, v_test_id,
        2, 'Section 2 — Questions 11-15', 'Complete the notes below. Write ONE WORD AND/OR A NUMBER for each answer.',
        'https://pub-7ae6bc0d9be44caba0b1258ca079ce53.r2.dev/listening-tests/test-14/full.mp3'
    );

    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, max_words)
      VALUES (v_qid, v_section_id, 11, 11, 'text_input', 'The main entrance is at the ____ of the plan.', 1);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["bottom"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, max_words)
      VALUES (v_qid, v_section_id, 12, 12, 'text_input', 'Reception is immediately ____ the entrance.', 1);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["inside"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, max_words)
      VALUES (v_qid, v_section_id, 13, 13, 'text_input', 'The art gallery is on the ____.', 1);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["left"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, max_words)
      VALUES (v_qid, v_section_id, 14, 14, 'text_input', 'The dance studio is on the ____.', 1);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["right"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, max_words)
      VALUES (v_qid, v_section_id, 15, 15, 'text_input', 'The exhibition hall is towards the ____ centre.', 1);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["rear"]');

    -- Section 2 — Questions 16-20 (Building Map Labelling)
    v_section_id := '8c88d71a-2d71-588c-8adc-c3b5b657fe4d';
    INSERT INTO test_sections (id, test_id, position, title, instructions, audio_url, image_url)
    VALUES (
        v_section_id, v_test_id,
        2, 'Section 2 — Questions 16-20 (Building Map Labelling)', 'Label the plan below. Choose the correct letter, A–H.',
        'https://pub-7ae6bc0d9be44caba0b1258ca079ce53.r2.dev/listening-tests/test-14/full.mp3',
        'https://pub-7ae6bc0d9be44caba0b1258ca079ce53.r2.dev/listening-tests/test-14/section-2-map.jpg'
    );

    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, options)
      VALUES (v_qid, v_section_id, 16, 16, 'map_label', 'Reception', '[{"letter": "A"}, {"letter": "B"}, {"letter": "C"}, {"letter": "D"}, {"letter": "E"}, {"letter": "F"}, {"letter": "G"}, {"letter": "H"}]'::jsonb);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["a"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, options)
      VALUES (v_qid, v_section_id, 17, 17, 'map_label', 'Art Gallery', '[{"letter": "A"}, {"letter": "B"}, {"letter": "C"}, {"letter": "D"}, {"letter": "E"}, {"letter": "F"}, {"letter": "G"}, {"letter": "H"}]'::jsonb);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["b"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, options)
      VALUES (v_qid, v_section_id, 18, 18, 'map_label', 'Dance Studio', '[{"letter": "A"}, {"letter": "B"}, {"letter": "C"}, {"letter": "D"}, {"letter": "E"}, {"letter": "F"}, {"letter": "G"}, {"letter": "H"}]'::jsonb);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["c"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, options)
      VALUES (v_qid, v_section_id, 19, 19, 'map_label', 'Music Room', '[{"letter": "A"}, {"letter": "B"}, {"letter": "C"}, {"letter": "D"}, {"letter": "E"}, {"letter": "F"}, {"letter": "G"}, {"letter": "H"}]'::jsonb);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["d"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, options)
      VALUES (v_qid, v_section_id, 20, 20, 'map_label', 'Pottery Workshop', '[{"letter": "A"}, {"letter": "B"}, {"letter": "C"}, {"letter": "D"}, {"letter": "E"}, {"letter": "F"}, {"letter": "G"}, {"letter": "H"}]'::jsonb);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["e"]');

    -- Section 3 — Questions 21-25
    v_section_id := '6d9121e5-c012-5076-94fa-f96a48c0d93d';
    INSERT INTO test_sections (id, test_id, position, title, instructions, audio_url)
    VALUES (
        v_section_id, v_test_id,
        3, 'Section 3 — Questions 21-25', 'Choose the correct letter, A, B or C.',
        'https://pub-7ae6bc0d9be44caba0b1258ca079ce53.r2.dev/listening-tests/test-14/full.mp3'
    );

    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, options)
      VALUES (v_qid, v_section_id, 21, 21, 'single_choice', 'What is the main focus of the project?', '[{"letter": "A", "text": "Food waste among university students"}, {"letter": "B", "text": "The price of university meals"}, {"letter": "C", "text": "Food production in local restaurants"}]'::jsonb);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["a"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, options)
      VALUES (v_qid, v_section_id, 22, 22, 'single_choice', 'Which students will participate?', '[{"letter": "A", "text": "Students in university residences"}, {"letter": "B", "text": "Students living in private accommodation"}, {"letter": "C", "text": "Postgraduate students only"}]'::jsonb);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["b"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, options)
      VALUES (v_qid, v_section_id, 23, 23, 'single_choice', 'How many questionnaire responses will they target?', '[{"letter": "A", "text": "240"}, {"letter": "B", "text": "260"}, {"letter": "C", "text": "300"}]'::jsonb);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["b"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, options)
      VALUES (v_qid, v_section_id, 24, 24, 'single_choice', 'How many students will record their food waste?', '[{"letter": "A", "text": "30"}, {"letter": "B", "text": "40"}, {"letter": "C", "text": "50"}]'::jsonb);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["b"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, options)
      VALUES (v_qid, v_section_id, 25, 25, 'single_choice', 'How long will the questionnaire remain open?', '[{"letter": "A", "text": "2 weeks"}, {"letter": "B", "text": "3 weeks"}, {"letter": "C", "text": "4 weeks"}]'::jsonb);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["b"]');

    -- Section 3 — Questions 26-30
    v_section_id := 'd9a4c28a-44a3-57fb-a7cf-0a210df18ba7';
    INSERT INTO test_sections (id, test_id, position, title, instructions, audio_url)
    VALUES (
        v_section_id, v_test_id,
        3, 'Section 3 — Questions 26-30', 'Who will be responsible for each task? Choose the correct letter, A, B or C.',
        'https://pub-7ae6bc0d9be44caba0b1258ca079ce53.r2.dev/listening-tests/test-14/full.mp3'
    );

    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, options)
      VALUES (v_qid, v_section_id, 26, 26, 'matching', 'Designing the questionnaire', '[{"letter": "A", "text": "Sophie"}, {"letter": "B", "text": "Adam"}, {"letter": "C", "text": "Both students"}]'::jsonb);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["a"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, options)
      VALUES (v_qid, v_section_id, 27, 27, 'matching', 'Organising food-waste records', '[{"letter": "A", "text": "Sophie"}, {"letter": "B", "text": "Adam"}, {"letter": "C", "text": "Both students"}]'::jsonb);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["b"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, options)
      VALUES (v_qid, v_section_id, 28, 28, 'matching', 'Recruiting participants', '[{"letter": "A", "text": "Sophie"}, {"letter": "B", "text": "Adam"}, {"letter": "C", "text": "Both students"}]'::jsonb);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["c"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, options)
      VALUES (v_qid, v_section_id, 29, 29, 'matching', 'Statistical analysis', '[{"letter": "A", "text": "Sophie"}, {"letter": "B", "text": "Adam"}, {"letter": "C", "text": "Both students"}]'::jsonb);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["a"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, options)
      VALUES (v_qid, v_section_id, 30, 30, 'matching', 'Writing the final recommendations', '[{"letter": "A", "text": "Sophie"}, {"letter": "B", "text": "Adam"}, {"letter": "C", "text": "Both students"}]'::jsonb);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["c"]');

    -- Section 4 — Questions 31-40
    v_section_id := '32c18369-eb20-5259-aa3f-015e47f5aaec';
    INSERT INTO test_sections (id, test_id, position, title, instructions, audio_url)
    VALUES (
        v_section_id, v_test_id,
        4, 'Section 4 — Questions 31-40', 'Complete the notes below. Write NO MORE THAN TWO WORDS for each answer.',
        'https://pub-7ae6bc0d9be44caba0b1258ca079ce53.r2.dev/listening-tests/test-14/full.mp3'
    );

    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, max_words)
      VALUES (v_qid, v_section_id, 31, 31, 'text_input', 'Wetlands include marshes, swamps and shallow ____ areas.', 2);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["coastal"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, max_words)
      VALUES (v_qid, v_section_id, 32, 32, 'text_input', 'One important function of wetlands is water ____.', 2);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["storage"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, max_words)
      VALUES (v_qid, v_section_id, 33, 33, 'text_input', 'Wetland soils and vegetation can hold significant quantities of ____.', 2);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["water"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, max_words)
      VALUES (v_qid, v_section_id, 34, 34, 'text_input', 'Wetlands can help reduce the impacts of ____.', 2);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["floods"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, max_words)
      VALUES (v_qid, v_section_id, 35, 35, 'text_input', 'Wetland vegetation and soils can trap pollutants and ____.', 2);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["sediment"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, max_words)
      VALUES (v_qid, v_section_id, 36, 36, 'text_input', 'Wetland plants can absorb certain ____ from water.', 2);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["nutrients"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, max_words)
      VALUES (v_qid, v_section_id, 37, 37, 'text_input', 'Wetlands provide habitat for many species and support biological ____.', 2);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["diversity"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, max_words)
      VALUES (v_qid, v_section_id, 38, 38, 'text_input', 'Wetland soils can store ____ for long periods.', 2);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["carbon"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, max_words)
      VALUES (v_qid, v_section_id, 39, 39, 'text_input', 'Wetlands have often been drained for agriculture, roads and urban ____.', 2);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["development"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, max_words)
      VALUES (v_qid, v_section_id, 40, 40, 'text_input', 'Returning water to previously drained areas can be part of wetland ____.', 2);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["restoration"]');

END $$;

COMMIT;