-- =====================================================================
-- Migration 0027 — Seed IELTS Listening Mock Tests 1-2
-- Generated by scripts/r2-listening-seed/generate_seed_sql_01_02.py — do
-- not hand-edit; re-run the generator instead if the source data changes.
--
-- Model (same as migrations/0024_seed_listening_tests_11_14.sql):
--   * 1 row in `tests`         -> the mock test (skill='listening')
--   * `test_sections` rows      -> one per question-type block
--   * `test_questions`/`test_answers` -> all 40 questions + answer key
--
-- NOTE: audio_url / image_url are NULL with a TODO comment below until
-- the corresponding files are uploaded to R2. To fill them in:
--   1. Put the audio files here (repo root):
--        scripts/r2-listening-seed/local_assets/TEST1/full.mp3
--        scripts/r2-listening-seed/local_assets/TEST2/full.mp3
--      (already committed for you)
--   2. node --env-file=.env scripts/r2-listening-seed/upload-to-r2.mjs
--   3. re-run this generator, then re-run this migration.
--
-- Run: psql -U postgres -d nexted_ielts -f migrations/0027_seed_listening_tests_01_02.sql
-- Idempotent: re-running replaces each test's sections/questions cleanly.
-- =====================================================================

BEGIN;

SET client_encoding = 'UTF8';

-- ---- Mock Test 1 -------------------------------------------------
DO $$
DECLARE
    v_test_id UUID := '306e8015-c549-5d44-97d7-ff369f728d66';
    v_section_id UUID;
    v_qid UUID;
BEGIN
    INSERT INTO tests (id, skill, title, description, instructions, duration_seconds, position, is_published)
    VALUES (
        v_test_id,
        'listening',
        'IELTS Listening Mock Test 1',
        'Section 1: enquiring about evening art classes at a community arts centre. Section 2: orientation guide to a new community library (floor plan labelling). Section 3: university students discussing a research project on urban green spaces and air temperature with their supervisor. Section 4: lecture on how plants adapt to dry environments.',
        'You will hear the recording once. Answer all 40 questions as you listen. Complete the notes and choose the correct letters as instructed in each section.',
        1680,
        1,
        TRUE
    )
    ON CONFLICT (id) DO UPDATE
        SET title = EXCLUDED.title,
            description = EXCLUDED.description,
            instructions = EXCLUDED.instructions,
            duration_seconds = EXCLUDED.duration_seconds,
            position = EXCLUDED.position,
            is_published = EXCLUDED.is_published,
            updated_at = now();

    DELETE FROM test_sections WHERE test_id = v_test_id;

    -- Section 1 — Questions 1-10
    v_section_id := 'c6f83b4f-7589-5cc3-8364-b3a5dbd799de';
    INSERT INTO test_sections (id, test_id, position, title, instructions, audio_url)
    VALUES (
        v_section_id, v_test_id,
        1, 'Section 1 — Questions 1-10', 'RIVERSIDE COMMUNITY ARTS CENTRE. Complete the notes below. Write ONE WORD AND/OR A NUMBER for each answer.',
        'https://pub-7ae6bc0d9be44caba0b1258ca079ce53.r2.dev/listening-tests/test-1/full.mp3'
    );

    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, max_words)
      VALUES (v_qid, v_section_id, 1, 1, 'text_input', 'Daniel is interested in a beginner ____ course.', 1);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["drawing"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, max_words)
      VALUES (v_qid, v_section_id, 2, 2, 'text_input', 'The main course takes place on ____ evenings.', 1);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["Wednesday"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, max_words)
      VALUES (v_qid, v_section_id, 3, 3, 'text_input', 'Classes run from 6:30 until ____.', 1);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["8:30", "8.30", "half past eight"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, max_words)
      VALUES (v_qid, v_section_id, 4, 4, 'text_input', 'The course lasts ____ weeks.', 1);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["6", "six"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, max_words)
      VALUES (v_qid, v_section_id, 5, 5, 'text_input', 'The course fee is £____.', 1);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["90", "ninety"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, max_words)
      VALUES (v_qid, v_section_id, 6, 6, 'text_input', 'Students need to bring a sketchbook, pencils and an ____.', 1);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["eraser"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, max_words)
      VALUES (v_qid, v_section_id, 7, 7, 'text_input', 'Recommended sketchbook size: ____.', 1);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["A4"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, max_words)
      VALUES (v_qid, v_section_id, 8, 8, 'text_input', 'An A4 sketchbook can be bought for £____.', 1);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["6", "six"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, max_words)
      VALUES (v_qid, v_section_id, 9, 9, 'text_input', 'Classes are held in Studio ____.', 1);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["3", "Three"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, max_words)
      VALUES (v_qid, v_section_id, 10, 10, 'text_input', 'The first class is on the ____ of October.', 1);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["seventh", "7th"]');

    -- Section 2 — Questions 11-15
    v_section_id := 'c84588fd-013f-580f-9e12-addacfcec4ce';
    INSERT INTO test_sections (id, test_id, position, title, instructions, audio_url)
    VALUES (
        v_section_id, v_test_id,
        2, 'Section 2 — Questions 11-15', 'Complete the notes below. Write ONE WORD AND/OR A NUMBER for each answer.',
        'https://pub-7ae6bc0d9be44caba0b1258ca079ce53.r2.dev/listening-tests/test-1/full.mp3'
    );

    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, max_words)
      VALUES (v_qid, v_section_id, 11, 11, 'text_input', 'The main entrance is on the ____ side.', 1);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["southern", "south"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, max_words)
      VALUES (v_qid, v_section_id, 12, 12, 'text_input', 'Reception is directly ____ the entrance.', 1);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["ahead"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, max_words)
      VALUES (v_qid, v_section_id, 13, 13, 'text_input', 'The general reading area is in the ____ of the building.', 1);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["centre", "center"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, max_words)
      VALUES (v_qid, v_section_id, 14, 14, 'text_input', 'The children''s library is on the ____ side.', 1);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["western", "west"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, max_words)
      VALUES (v_qid, v_section_id, 15, 15, 'text_input', 'The computer room is on the ____ side.', 1);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["eastern", "east"]');

    -- Section 2 — Questions 16-20 (Floor Plan Labelling)
    v_section_id := 'f7e7b4bc-20cc-5639-9f93-60c7fa1060f2';
    INSERT INTO test_sections (id, test_id, position, title, instructions, audio_url, image_url)
    VALUES (
        v_section_id, v_test_id,
        2, 'Section 2 — Questions 16-20 (Floor Plan Labelling)', 'Label the plan below. Choose the correct letter, A–H.',
        'https://pub-7ae6bc0d9be44caba0b1258ca079ce53.r2.dev/listening-tests/test-1/full.mp3',
        'https://pub-7ae6bc0d9be44caba0b1258ca079ce53.r2.dev/listening-tests/test-1/section-2-map.jpg'
    );

    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, options)
      VALUES (v_qid, v_section_id, 16, 16, 'map_label', 'General reading area', '[{"letter": "A"}, {"letter": "B"}, {"letter": "C"}, {"letter": "D"}, {"letter": "E"}, {"letter": "F"}, {"letter": "G"}, {"letter": "H"}]'::jsonb);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["a"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, options)
      VALUES (v_qid, v_section_id, 17, 17, 'map_label', 'Children''s library', '[{"letter": "A"}, {"letter": "B"}, {"letter": "C"}, {"letter": "D"}, {"letter": "E"}, {"letter": "F"}, {"letter": "G"}, {"letter": "H"}]'::jsonb);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["b"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, options)
      VALUES (v_qid, v_section_id, 18, 18, 'map_label', 'Computer room', '[{"letter": "A"}, {"letter": "B"}, {"letter": "C"}, {"letter": "D"}, {"letter": "E"}, {"letter": "F"}, {"letter": "G"}, {"letter": "H"}]'::jsonb);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["c"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, options)
      VALUES (v_qid, v_section_id, 19, 19, 'map_label', 'Café', '[{"letter": "A"}, {"letter": "B"}, {"letter": "C"}, {"letter": "D"}, {"letter": "E"}, {"letter": "F"}, {"letter": "G"}, {"letter": "H"}]'::jsonb);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["d"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, options)
      VALUES (v_qid, v_section_id, 20, 20, 'map_label', 'Study room', '[{"letter": "A"}, {"letter": "B"}, {"letter": "C"}, {"letter": "D"}, {"letter": "E"}, {"letter": "F"}, {"letter": "G"}, {"letter": "H"}]'::jsonb);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["e"]');

    -- Section 3 — Questions 21-25
    v_section_id := 'dcc6719b-3ef2-5fd8-9b3b-bab7bd0a1043';
    INSERT INTO test_sections (id, test_id, position, title, instructions, audio_url)
    VALUES (
        v_section_id, v_test_id,
        3, 'Section 3 — Questions 21-25', 'Choose the correct letter, A, B or C.',
        'https://pub-7ae6bc0d9be44caba0b1258ca079ce53.r2.dev/listening-tests/test-1/full.mp3'
    );

    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, options)
      VALUES (v_qid, v_section_id, 21, 21, 'single_choice', 'Why did the students change their original research idea?', '[{"letter": "A", "text": "There were too few parks to study."}, {"letter": "B", "text": "Too many locations would make consistent data collection difficult."}, {"letter": "C", "text": "The university refused permission."}]'::jsonb);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["b"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, options)
      VALUES (v_qid, v_section_id, 22, 22, 'single_choice', 'What is the revised research focus?', '[{"letter": "A", "text": "Tree density and local air temperature"}, {"letter": "B", "text": "Air pollution in city centres"}, {"letter": "C", "text": "Satellite technology and urban planning"}]'::jsonb);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["a"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, options)
      VALUES (v_qid, v_section_id, 23, 23, 'single_choice', 'Why will they use ground measurements?', '[{"letter": "A", "text": "Satellite data is unavailable."}, {"letter": "B", "text": "Ground measurements provide more street-level detail."}, {"letter": "C", "text": "Ground measurements are cheaper."}]'::jsonb);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["b"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, options)
      VALUES (v_qid, v_section_id, 24, 24, 'single_choice', 'How often will measurements be taken?', '[{"letter": "A", "text": "Once a day"}, {"letter": "B", "text": "Twice a day"}, {"letter": "C", "text": "Three times a day"}]'::jsonb);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["c"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, options)
      VALUES (v_qid, v_section_id, 25, 25, 'single_choice', 'How long will the study last?', '[{"letter": "A", "text": "Two weeks"}, {"letter": "B", "text": "Three weeks"}, {"letter": "C", "text": "Four weeks"}]'::jsonb);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["b"]');

    -- Section 3 — Questions 26-30
    v_section_id := 'd806ba6d-a43e-5592-a4fd-fd10564e84f3';
    INSERT INTO test_sections (id, test_id, position, title, instructions, audio_url)
    VALUES (
        v_section_id, v_test_id,
        3, 'Section 3 — Questions 26-30', 'Who will be responsible for each task? A. Liam  B. Sofia  C. Both students',
        'https://pub-7ae6bc0d9be44caba0b1258ca079ce53.r2.dev/listening-tests/test-1/full.mp3'
    );

    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, options)
      VALUES (v_qid, v_section_id, 26, 26, 'matching', 'Organising temperature measurements', '[{"letter": "A", "text": "Liam"}, {"letter": "B", "text": "Sofia"}, {"letter": "C", "text": "Both students"}]'::jsonb);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["a"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, options)
      VALUES (v_qid, v_section_id, 27, 27, 'matching', 'Analysing satellite images', '[{"letter": "A", "text": "Liam"}, {"letter": "B", "text": "Sofia"}, {"letter": "C", "text": "Both students"}]'::jsonb);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["b"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, options)
      VALUES (v_qid, v_section_id, 28, 28, 'matching', 'Contacting neighbourhood groups', '[{"letter": "A", "text": "Liam"}, {"letter": "B", "text": "Sofia"}, {"letter": "C", "text": "Both students"}]'::jsonb);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["b"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, options)
      VALUES (v_qid, v_section_id, 29, 29, 'matching', 'Cleaning the final dataset', '[{"letter": "A", "text": "Liam"}, {"letter": "B", "text": "Sofia"}, {"letter": "C", "text": "Both students"}]'::jsonb);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["c"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, options)
      VALUES (v_qid, v_section_id, 30, 30, 'matching', 'Writing the discussion', '[{"letter": "A", "text": "Liam"}, {"letter": "B", "text": "Sofia"}, {"letter": "C", "text": "Both students"}]'::jsonb);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["c"]');

    -- Section 4 — Questions 31-40
    v_section_id := '48c1f0ef-f608-5fce-9df5-0085b4a0afa6';
    INSERT INTO test_sections (id, test_id, position, title, instructions, audio_url)
    VALUES (
        v_section_id, v_test_id,
        4, 'Section 4 — Questions 31-40', 'Complete the notes below. Write NO MORE THAN TWO WORDS AND/OR A NUMBER for each answer.',
        'https://pub-7ae6bc0d9be44caba0b1258ca079ce53.r2.dev/listening-tests/test-1/full.mp3'
    );

    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, max_words)
      VALUES (v_qid, v_section_id, 31, 31, 'text_input', 'Water is involved in photosynthesis, nutrient transport and maintaining cell ____.', 2);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["structure"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, max_words)
      VALUES (v_qid, v_section_id, 32, 32, 'text_input', 'Plants lose water mainly through openings called ____.', 2);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["stomata"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, max_words)
      VALUES (v_qid, v_section_id, 33, 33, 'text_input', 'Stomata allow ____ to enter leaves for photosynthesis.', 2);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["carbon dioxide", "CO2"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, max_words)
      VALUES (v_qid, v_section_id, 34, 34, 'text_input', 'Some dry-environment plants have small or ____ leaves.', 2);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["narrow"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, max_words)
      VALUES (v_qid, v_section_id, 35, 35, 'text_input', 'Succulent plants can store water in thick leaves or ____.', 2);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["stems"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, max_words)
      VALUES (v_qid, v_section_id, 36, 36, 'text_input', 'Some desert plants develop very ____ roots.', 2);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["deep"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, max_words)
      VALUES (v_qid, v_section_id, 37, 37, 'text_input', 'Other plants have extensive ____ root systems.', 2);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["shallow"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, max_words)
      VALUES (v_qid, v_section_id, 38, 38, 'text_input', 'Some plants carry out more gas exchange at ____.', 2);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["night"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, max_words)
      VALUES (v_qid, v_section_id, 39, 39, 'text_input', 'Slow growth can reduce the amount of water and ____ required for new tissue.', 2);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["energy"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, max_words)
      VALUES (v_qid, v_section_id, 40, 40, 'text_input', 'Changes in rainfall patterns may cause longer or less predictable periods of ____.', 2);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["drought"]');

END $$;

-- ---- Mock Test 2 -------------------------------------------------
DO $$
DECLARE
    v_test_id UUID := 'dc25665c-ae66-506a-b2a6-e2a46f120f64';
    v_section_id UUID;
    v_qid UUID;
BEGIN
    INSERT INTO tests (id, skill, title, description, instructions, duration_seconds, position, is_published)
    VALUES (
        v_test_id,
        'listening',
        'IELTS Listening Mock Test 2',
        'Section 1: enquiring about membership at a local sports centre. Section 2: visitor information officer describing three visitor packages at a heritage centre. Section 3: university students discussing a research project on student cycling habits with their supervisor. Section 4: lecture on the importance of bees in ecosystems.',
        'You will hear the recording once. Answer all 40 questions as you listen. Complete the notes and choose the correct letters as instructed in each section.',
        1680,
        2,
        TRUE
    )
    ON CONFLICT (id) DO UPDATE
        SET title = EXCLUDED.title,
            description = EXCLUDED.description,
            instructions = EXCLUDED.instructions,
            duration_seconds = EXCLUDED.duration_seconds,
            position = EXCLUDED.position,
            is_published = EXCLUDED.is_published,
            updated_at = now();

    DELETE FROM test_sections WHERE test_id = v_test_id;

    -- Section 1 — Questions 1-10
    v_section_id := '5d08c839-e24f-538b-9774-61237ced5c82';
    INSERT INTO test_sections (id, test_id, position, title, instructions, audio_url)
    VALUES (
        v_section_id, v_test_id,
        1, 'Section 1 — Questions 1-10', 'LAKESIDE SPORTS CENTRE. Complete the notes below. Write ONE WORD AND/OR A NUMBER for each answer.',
        'https://pub-7ae6bc0d9be44caba0b1258ca079ce53.r2.dev/listening-tests/test-2/full.mp3'
    );

    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, max_words)
      VALUES (v_qid, v_section_id, 1, 1, 'text_input', 'Nina is mainly interested in the gym and the ____.', 1);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["swimming"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, max_words)
      VALUES (v_qid, v_section_id, 2, 2, 'text_input', 'The standard membership includes basic fitness ____.', 1);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["classes"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, max_words)
      VALUES (v_qid, v_section_id, 3, 3, 'text_input', 'The membership costs $____ per month.', 1);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["38", "thirty-eight"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, max_words)
      VALUES (v_qid, v_section_id, 4, 4, 'text_input', 'The joining fee is $____.', 1);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["20", "twenty"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, max_words)
      VALUES (v_qid, v_section_id, 5, 5, 'text_input', 'The joining fee is waived if members pay for ____ months in advance.', 1);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["6", "six"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, max_words)
      VALUES (v_qid, v_section_id, 6, 6, 'text_input', 'Weekday opening time: ____ a.m.', 1);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["6", "six"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, max_words)
      VALUES (v_qid, v_section_id, 7, 7, 'text_input', 'Weekday closing time: ____ p.m.', 1);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["10", "ten"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, max_words)
      VALUES (v_qid, v_section_id, 8, 8, 'text_input', 'Saturday opening hours are ____ until 8 p.m.', 1);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["8", "eight"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, max_words)
      VALUES (v_qid, v_section_id, 9, 9, 'text_input', 'Group classes are booked through the member ____.', 1);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["app"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, max_words)
      VALUES (v_qid, v_section_id, 10, 10, 'text_input', 'Members should check the swimming ____ before attending.', 1);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["timetable"]');

    -- Section 2 — Questions 11-15
    v_section_id := 'ef903847-60ef-5b68-89a3-05fd7463b69d';
    INSERT INTO test_sections (id, test_id, position, title, instructions, audio_url)
    VALUES (
        v_section_id, v_test_id,
        2, 'Section 2 — Questions 11-15', 'Complete the notes below. Write ONE WORD AND/OR A NUMBER for each answer.',
        'https://pub-7ae6bc0d9be44caba0b1258ca079ce53.r2.dev/listening-tests/test-2/full.mp3'
    );

    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, max_words)
      VALUES (v_qid, v_section_id, 11, 11, 'text_input', 'Option A focuses on the main historic ____.', 1);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["building"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, max_words)
      VALUES (v_qid, v_section_id, 12, 12, 'text_input', 'Option B includes a visit to the ____.', 1);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["greenhouse"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, max_words)
      VALUES (v_qid, v_section_id, 13, 13, 'text_input', 'Option C is designed mainly for ____.', 1);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["families"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, max_words)
      VALUES (v_qid, v_section_id, 14, 14, 'text_input', 'The History Tour lasts ____ minutes.', 1);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["90", "ninety"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, max_words)
      VALUES (v_qid, v_section_id, 15, 15, 'text_input', 'The Garden Tour lasts ____ minutes.', 1);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["75", "seventy-five"]');

    -- Section 2 — Questions 16-20 (Visitor Package Options)
    v_section_id := 'f5f3d8a3-8368-5307-b743-52afa17efe09';
    INSERT INTO test_sections (id, test_id, position, title, instructions, audio_url, image_url)
    VALUES (
        v_section_id, v_test_id,
        2, 'Section 2 — Questions 16-20 (Visitor Package Options)', 'Choose the correct option, A, B or C.',
        'https://pub-7ae6bc0d9be44caba0b1258ca079ce53.r2.dev/listening-tests/test-2/full.mp3',
        'https://pub-7ae6bc0d9be44caba0b1258ca079ce53.r2.dev/listening-tests/test-2/section-2-visual-options.jpg'
    );

    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, options)
      VALUES (v_qid, v_section_id, 16, 16, 'single_choice', 'Which package includes the archive room?', '[{"letter": "A", "text": "History Tour"}, {"letter": "B", "text": "Garden Tour"}, {"letter": "C", "text": "Family Discovery Tour"}]'::jsonb);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["a"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, options)
      VALUES (v_qid, v_section_id, 17, 17, 'single_choice', 'Which package includes a plant demonstration?', '[{"letter": "A", "text": "History Tour"}, {"letter": "B", "text": "Garden Tour"}, {"letter": "C", "text": "Family Discovery Tour"}]'::jsonb);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["b"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, options)
      VALUES (v_qid, v_section_id, 18, 18, 'single_choice', 'Which package includes a children''s activity room?', '[{"letter": "A", "text": "History Tour"}, {"letter": "B", "text": "Garden Tour"}, {"letter": "C", "text": "Family Discovery Tour"}]'::jsonb);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["c"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, options)
      VALUES (v_qid, v_section_id, 19, 19, 'single_choice', 'Which package is best for visitors mainly interested in local history?', '[{"letter": "A", "text": "History Tour"}, {"letter": "B", "text": "Garden Tour"}, {"letter": "C", "text": "Family Discovery Tour"}]'::jsonb);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["a"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, options)
      VALUES (v_qid, v_section_id, 20, 20, 'single_choice', 'Which package is recommended for families with young children?', '[{"letter": "A", "text": "History Tour"}, {"letter": "B", "text": "Garden Tour"}, {"letter": "C", "text": "Family Discovery Tour"}]'::jsonb);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["c"]');

    -- Section 3 — Questions 21-25
    v_section_id := '8b86165c-babc-5cc0-8463-6fa20e942922';
    INSERT INTO test_sections (id, test_id, position, title, instructions, audio_url)
    VALUES (
        v_section_id, v_test_id,
        3, 'Section 3 — Questions 21-25', 'Choose the correct letter, A, B or C.',
        'https://pub-7ae6bc0d9be44caba0b1258ca079ce53.r2.dev/listening-tests/test-2/full.mp3'
    );

    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, options)
      VALUES (v_qid, v_section_id, 21, 21, 'single_choice', 'What is the main focus of the research?', '[{"letter": "A", "text": "Public transport costs"}, {"letter": "B", "text": "Factors influencing students'' decision to cycle"}, {"letter": "C", "text": "Cycling accidents near universities"}]'::jsonb);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["b"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, options)
      VALUES (v_qid, v_section_id, 22, 22, 'single_choice', 'Why did the students abandon their original idea?', '[{"letter": "A", "text": "It was too broad."}, {"letter": "B", "text": "They could not recruit participants."}, {"letter": "C", "text": "There was insufficient data."}]'::jsonb);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["a"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, options)
      VALUES (v_qid, v_section_id, 23, 23, 'single_choice', 'How many interviews will they conduct?', '[{"letter": "A", "text": "20"}, {"letter": "B", "text": "30"}, {"letter": "C", "text": "40"}]'::jsonb);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["a"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, options)
      VALUES (v_qid, v_section_id, 24, 24, 'single_choice', 'Which students will be excluded from the survey?', '[{"letter": "A", "text": "Students who cycle regularly"}, {"letter": "B", "text": "Students living more than ten kilometres away"}, {"letter": "C", "text": "Students living in university accommodation"}]'::jsonb);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["c"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, options)
      VALUES (v_qid, v_section_id, 25, 25, 'single_choice', 'How long will they collect data?', '[{"letter": "A", "text": "Two weeks"}, {"letter": "B", "text": "Three weeks"}, {"letter": "C", "text": "Four weeks"}]'::jsonb);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["b"]');

    -- Section 3 — Questions 26-30
    v_section_id := '27ff5322-a616-5532-bdd8-c525f73a6ccf';
    INSERT INTO test_sections (id, test_id, position, title, instructions, audio_url)
    VALUES (
        v_section_id, v_test_id,
        3, 'Section 3 — Questions 26-30', 'Who will be responsible for each task? A. Alex  B. Maya  C. Both students',
        'https://pub-7ae6bc0d9be44caba0b1258ca079ce53.r2.dev/listening-tests/test-2/full.mp3'
    );

    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, options)
      VALUES (v_qid, v_section_id, 26, 26, 'matching', 'Designing the questionnaire', '[{"letter": "A", "text": "Alex"}, {"letter": "B", "text": "Maya"}, {"letter": "C", "text": "Both students"}]'::jsonb);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["a"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, options)
      VALUES (v_qid, v_section_id, 27, 27, 'matching', 'Conducting interviews', '[{"letter": "A", "text": "Alex"}, {"letter": "B", "text": "Maya"}, {"letter": "C", "text": "Both students"}]'::jsonb);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["b"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, options)
      VALUES (v_qid, v_section_id, 28, 28, 'matching', 'Recruiting participants', '[{"letter": "A", "text": "Alex"}, {"letter": "B", "text": "Maya"}, {"letter": "C", "text": "Both students"}]'::jsonb);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["b"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, options)
      VALUES (v_qid, v_section_id, 29, 29, 'matching', 'Analysing questionnaire data', '[{"letter": "A", "text": "Alex"}, {"letter": "B", "text": "Maya"}, {"letter": "C", "text": "Both students"}]'::jsonb);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["a"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, options)
      VALUES (v_qid, v_section_id, 30, 30, 'matching', 'Writing the discussion and conclusion', '[{"letter": "A", "text": "Alex"}, {"letter": "B", "text": "Maya"}, {"letter": "C", "text": "Both students"}]'::jsonb);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["c"]');

    -- Section 4 — Questions 31-40
    v_section_id := 'f602046c-d0f3-5fc9-bebb-c5dc03c63574';
    INSERT INTO test_sections (id, test_id, position, title, instructions, audio_url)
    VALUES (
        v_section_id, v_test_id,
        4, 'Section 4 — Questions 31-40', 'Complete the notes below. Write NO MORE THAN TWO WORDS AND/OR A NUMBER for each answer.',
        'https://pub-7ae6bc0d9be44caba0b1258ca079ce53.r2.dev/listening-tests/test-2/full.mp3'
    );

    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, max_words)
      VALUES (v_qid, v_section_id, 31, 31, 'text_input', 'One of the most important roles of bees is ____.', 2);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["pollination"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, max_words)
      VALUES (v_qid, v_section_id, 32, 32, 'text_input', 'Bees transfer pollen between ____.', 2);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["flowers"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, max_words)
      VALUES (v_qid, v_section_id, 33, 33, 'text_input', 'Bees collect both pollen and ____.', 2);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["nectar"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, max_words)
      VALUES (v_qid, v_section_id, 34, 34, 'text_input', 'Honey bees live socially in ____.', 2);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["colonies"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, max_words)
      VALUES (v_qid, v_section_id, 35, 35, 'text_input', 'Many other bee species are ____.', 2);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["solitary"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, max_words)
      VALUES (v_qid, v_section_id, 36, 36, 'text_input', 'One major environmental pressure is habitat ____.', 2);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["loss"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, max_words)
      VALUES (v_qid, v_section_id, 37, 37, 'text_input', 'Some pesticides may affect bees'' ability to ____.', 2);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["navigate"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, max_words)
      VALUES (v_qid, v_section_id, 38, 38, 'text_input', 'Climate change can alter the timing of plant ____.', 2);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["flowering"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, max_words)
      VALUES (v_qid, v_section_id, 39, 39, 'text_input', 'Gardens and parks can provide bees with sources of ____.', 2);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["food"]');
    v_qid := uuid_generate_v4();
    INSERT INTO test_questions (id, section_id, qnumber, position, type, prompt, max_words)
      VALUES (v_qid, v_section_id, 40, 40, 'text_input', 'Some solitary bees use cavities in ____ for nesting.', 2);
    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, '["wood"]');

END $$;

COMMIT;