import React from 'react';
import { GlassPanel } from '../components/ui/GlassPanel';
import { BackLink } from '../components/ui/BackLink';

interface TermsViewProps {
  onNavigateToLanding: () => void;
}

// Standalone, unauthenticated page -- same shell pattern as Login/Signup/
// ForgotPassword (header with logo + BackLink, single centered panel,
// footer), just with static content instead of a form. Content mirrors
// the approved draft 1:1 (see the "IELTS AI — Terms & Conditions and
// Privacy Policy (Draft)" doc) -- update both together if either changes.
export const TermsView: React.FC<TermsViewProps> = ({ onNavigateToLanding }) => {
  return (
    <div className="min-h-screen bg-[var(--bg)] text-[var(--text)] flex flex-col justify-between relative overflow-hidden">
      <div className="bg-layer">
        <div className="bg-pattern" />
      </div>

      <header className="relative z-10 border-b border-[var(--border)] px-6 py-4 flex items-center justify-between">
        <div
          onClick={onNavigateToLanding}
          className="flex items-center gap-2 cursor-pointer hover:opacity-80 transition-opacity overflow-hidden min-w-0"
        >
          <img src="/branding/ielts-ai-mascot-full.png" alt="IELTS AI" className="h-10 w-auto object-contain shrink-0" />
          <img src="/branding/ielts-ai-wordmark-dark.png" alt="IELTS AI by nextED." className="brand-wordmark-dark h-9 w-auto object-contain" />
          <img src="/branding/ielts-ai-wordmark-light.png" alt="IELTS AI by nextED." className="brand-wordmark-light h-9 w-auto object-contain" />
        </div>

        <BackLink onClick={onNavigateToLanding}>Back to Home</BackLink>
      </header>

      <main className="relative z-10 flex-1 flex items-start justify-center p-4 md:p-8">
        <div className="w-full max-w-3xl space-y-6 py-6">
          <div className="text-center space-y-2">
            <h1 className="font-display text-3xl font-extrabold text-[var(--text)]">
              Terms &amp; Conditions
            </h1>
            <p className="text-xs text-[var(--text-dim)]">Last updated September 17, 2026</p>
          </div>

          <GlassPanel className="p-6 md:p-8 border border-[var(--border)] shadow-2xl space-y-6 text-sm leading-relaxed text-[var(--text-dim)]">
            <p className="p-3.5 rounded-xl bg-[var(--accent-a)]/10 border border-[var(--accent-a)]/30 text-[var(--text)] font-semibold">
              By creating an account or registering on IELTS AI ("the Platform"), operated by NextEd
              ("we", "us", "our"), you confirm that you have read, understood, and agree to be bound by
              these Terms &amp; Conditions and our Privacy Policy. If you do not agree, please do not
              register for or use the Platform.
            </p>

            <section className="space-y-2">
              <h2 className="font-display text-lg font-bold text-[var(--text)]">1. Acceptance of These Terms</h2>
              <p>
                Registration requires a valid mobile phone number for identity verification (via OTP)
                and your agreement to the data practices described in the Privacy Policy, including the
                use of test submissions to train our AI systems.
              </p>
            </section>

            <section className="space-y-2">
              <h2 className="font-display text-lg font-bold text-[var(--text)]">2. Eligibility</h2>
              <p>
                You must be at least 13 years old to create an account. If you are between 13 and the
                age of majority in your jurisdiction, you confirm that a parent or legal guardian has
                reviewed and agreed to these Terms on your behalf.
              </p>
            </section>

            <section className="space-y-2">
              <h2 className="font-display text-lg font-bold text-[var(--text)]">3. Your Account</h2>
              <p>
                You are responsible for keeping your phone number and password confidential and for
                all activity under your account. Notify us immediately if you suspect unauthorized
                access. We may suspend or terminate accounts that provide false registration
                information.
              </p>
            </section>

            <section className="space-y-2">
              <h2 className="font-display text-lg font-bold text-[var(--text)]">4. Description of the Service</h2>
              <p>
                IELTS AI provides AI-assisted IELTS exam preparation, including practice tests across
                Listening, Reading, Writing, and Speaking, automated scoring, feedback, and progress
                tracking. Scoring and feedback are generated by automated systems (including
                third-party AI models) and are intended as practice guidance only — they are not
                official IELTS scores and are not guaranteed to match your actual exam result.
              </p>
            </section>

            <section className="space-y-2">
              <h2 className="font-display text-lg font-bold text-[var(--text)]">5. Use of Your Test Data to Train Our Own AI</h2>
              <p className="text-[var(--text)] font-semibold">
                By using the Platform, you acknowledge and agree that we may use your test
                submissions, responses, transcripts, and associated results ("Test Data") to train,
                fine-tune, and improve our own proprietary AI models and language models (LLMs), with
                the intention of progressively shifting our evaluation and feedback systems onto AI
                models that we develop and control.
              </p>
              <p>
                We may use Test Data in de-identified or aggregated form for this purpose. We will not
                publicly attribute specific Test Data to your name outside the Platform. This training
                use is a condition of using the Service, alongside the personalization uses described
                in our Privacy Policy.
              </p>
            </section>

            <section className="space-y-2">
              <h2 className="font-display text-lg font-bold text-[var(--text)]">6. Acceptable Use</h2>
              <p>
                You agree not to: (a) share your account with others or access another user's account;
                (b) use automated tools, scripts, or bots to complete tests or manipulate scoring; (c)
                copy, resell, scrape, or redistribute Platform content or test materials; (d) upload
                unlawful, abusive, or infringing content; or (e) attempt to reverse-engineer, probe, or
                interfere with the Platform's AI systems or infrastructure.
              </p>
            </section>

            <section className="space-y-2">
              <h2 className="font-display text-lg font-bold text-[var(--text)]">7. Intellectual Property</h2>
              <p>
                All test content, questions, branding, software, and platform design are the property
                of NextEd or its licensors. You retain ownership of the personal responses you submit,
                subject to the license granted to us in Section 5 to use that data for training and
                service improvement.
              </p>
            </section>

            <section className="space-y-2">
              <h2 className="font-display text-lg font-bold text-[var(--text)]">8. Disclaimers &amp; Limitation of Liability</h2>
              <p>
                The Platform is provided "as is." We do not guarantee that practice scores will predict
                your official IELTS band score, that the Service will be uninterrupted or error-free,
                or that AI-generated feedback will be free of mistakes. To the maximum extent permitted
                by law, NextEd is not liable for indirect, incidental, or consequential damages arising
                from your use of the Platform, including reliance on practice scores or feedback when
                making exam, visa, or academic decisions.
              </p>
            </section>

            <section className="space-y-2">
              <h2 className="font-display text-lg font-bold text-[var(--text)]">9. Suspension &amp; Termination</h2>
              <p>
                We may suspend or terminate your account at any time for violation of these Terms,
                suspected fraud, or misuse of the Platform. You may close your account at any time by
                contacting support; note that Test Data already used to train our models cannot be
                retroactively removed from a trained model, though we will stop further use of your
                data going forward.
              </p>
            </section>

            <section className="space-y-2">
              <h2 className="font-display text-lg font-bold text-[var(--text)]">10. Changes to These Terms</h2>
              <p>
                We may update these Terms from time to time. Material changes will be notified through
                the Platform or via SMS to your registered phone number. Continued use of the Platform
                after changes take effect constitutes acceptance of the revised Terms.
              </p>
            </section>

            <section className="space-y-2">
              <h2 className="font-display text-lg font-bold text-[var(--text)]">11. Governing Law</h2>
              <p>
                These Terms are governed by the laws of Bangladesh, without regard to conflict-of-law
                principles.
              </p>
            </section>

            <section className="space-y-2">
              <h2 className="font-display text-lg font-bold text-[var(--text)]">12. Contact</h2>
              <p>
                Questions about these Terms can be directed to NextEd support through the Platform's
                contact channels.
              </p>
            </section>
          </GlassPanel>
        </div>
      </main>

      <footer className="font-michroma relative z-10 py-4 text-center text-xs tracking-wide text-[var(--text-faint)] border-t border-[var(--border)]">
        IELTS AI • Phone Authentication • Powered by PostgreSQL
      </footer>
    </div>
  );
};
