#!/usr/bin/env python3
"""
Generates migrations/0024_seed_listening_tests_11_14.sql from:
  - scripts/r2-listening-seed/manifest.json     (topics, sections, all 40
    questions + answer keys per test, extracted from the original
    ElevenLabs production scripts)
  - scripts/r2-listening-seed/asset-urls.json    (R2 public URL per
    test/file, written by upload-to-r2.mjs)

Follows the same conventions already used for this app's other listening
test (migrations/seed_listening_test_77*.sql):
  * 1 row in `tests` per mock test (skill='listening')
  * `test_sections` rows carry audio_url / image_url — a single IELTS
    section can be split into multiple test_sections rows when it mixes
    question types (Section 2: notes + map labelling; Section 3: single
    choice + matching). Every test_sections row for a given test shares
    that SAME ONE audio_url (test.audio_local, e.g. "full.mp3") — the
    whole test is one continuous recording, exactly like the real exam;
    there's no need to cut it into per-section files.
  * `test_questions.options` uses [{"letter":"A","text":"..."}] (map_label
    options omit "text" — the letters are shown on the image itself).
  * `test_answers.accepted` stores letter answers lowercase.

Safe to run before every asset is uploaded: any section whose audio_url
(or image_url) isn't in asset-urls.json yet gets NULL with a TODO comment,
so you can seed the questions now and backfill media URLs later by
re-running this script once upload-to-r2.mjs has more to report.

Run from repo root:
    python3 scripts/r2-listening-seed/generate_seed_sql.py
"""
import json
import uuid
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent.parent
SEED_DIR = Path(__file__).resolve().parent
OUT_PATH = ROOT / "migrations" / "0024_seed_listening_tests_11_14.sql"

# Fixed namespace, distinct from the writing test bank's (22222222-...) and
# from test 77's hand-picked id — so re-running this generator always
# reproduces the SAME ids (idempotent; ON CONFLICT / DELETE+INSERT key off
# them).
NAMESPACE = uuid.UUID("44444444-4444-4444-4444-444444444444")


def test_uuid(num: int) -> str:
    return str(uuid.uuid5(NAMESPACE, f"listening-test-{num}"))


def section_uuid(num: int, key: str) -> str:
    return str(uuid.uuid5(NAMESPACE, f"listening-test-{num}-section-{key}"))


def sql_quote(s: str) -> str:
    return "'" + s.replace("'", "''") + "'"


def sql_quote_or_null(s):
    return "NULL" if s is None else sql_quote(s)


def options_jsonb(options):
    if not options:
        return "NULL"
    return sql_quote(json.dumps(options)) + "::jsonb"


def main():
    manifest = json.loads((SEED_DIR / "manifest.json").read_text(encoding="utf-8"))
    urls_path = SEED_DIR / "asset-urls.json"
    urls = json.loads(urls_path.read_text(encoding="utf-8")) if urls_path.exists() else {}

    lines = []
    lines.append("-- =====================================================================")
    lines.append("-- Migration 0024 — Seed IELTS Listening Mock Tests 11-14")
    lines.append("-- Generated by scripts/r2-listening-seed/generate_seed_sql.py — do not")
    lines.append("-- hand-edit; re-run the generator instead if the source data changes.")
    lines.append("--")
    lines.append("-- Model (same as migrations/seed_listening_test_77*.sql):")
    lines.append("--   * 1 row in `tests`         -> the mock test (skill='listening')")
    lines.append("--   * `test_sections` rows      -> one per question-type block; a single")
    lines.append("--                                  IELTS section can have >1 row sharing")
    lines.append("--                                  the same merged audio_url")
    lines.append("--   * `test_questions`/`test_answers` -> all 40 questions + answer key")
    lines.append("--")
    lines.append('-- Run: psql "$DATABASE_URL" -f migrations/0024_seed_listening_tests_11_14.sql')
    lines.append("-- Idempotent: re-running replaces each test's sections/questions cleanly.")
    lines.append("-- =====================================================================")
    lines.append("")
    lines.append("BEGIN;")
    lines.append("")
    # Force UTF-8 for this session BEFORE any multibyte text (section titles use
    # em/en dashes, U+2014/U+2013) is sent. Without this, psql on Windows falls
    # back to the OS codepage (e.g. Windows-1252) as client_encoding, and the
    # server "converts" each UTF-8 byte of a dash as if it were a WIN1252
    # character — corrupting it into 3 stored characters (the classic "â€\x94"
    # / "â€"" mojibake). This one line prevents that at the source.
    lines.append("SET client_encoding = 'UTF8';")
    lines.append("")

    missing_assets = []

    for test in manifest["tests"]:
        num = test["num"]
        tid = test_uuid(num)
        # "position" (display ordering) can differ from "num" (used only to
        # derive the stable id above, via test_uuid) -- e.g. tests 11-14 were
        # renumbered to display as 3-6 (see migrations/0028_rename_listening_tests_11_14_to_3_6.sql)
        # while keeping their original ids so mock_test_sections links stay intact.
        # Falls back to num when no override is set.
        position = test.get("position", num)
        title = test["title"]
        description = test["description"]
        instructions = (
            "You will hear the recording once. Answer all 40 questions as you "
            "listen. Complete the notes and choose the correct letters as "
            "instructed in each section."
        )

        lines.append(f"-- ---- Mock Test {num} " + "-" * max(0, 50 - len(str(num))))
        lines.append("DO $$")
        lines.append("DECLARE")
        lines.append(f"    v_test_id UUID := {sql_quote(tid)};")
        lines.append("    v_section_id UUID;")
        lines.append("    v_qid UUID;")
        lines.append("BEGIN")
        lines.append("    INSERT INTO tests (id, skill, title, description, instructions, duration_seconds, position, is_published)")
        lines.append("    VALUES (")
        lines.append("        v_test_id,")
        lines.append("        'listening',")
        lines.append(f"        {sql_quote(title)},")
        lines.append(f"        {sql_quote(description)},")
        lines.append(f"        {sql_quote(instructions)},")
        lines.append(f"        {test['duration_seconds']},")
        lines.append(f"        {position},")
        lines.append("        TRUE")
        lines.append("    )")
        lines.append("    ON CONFLICT (id) DO UPDATE")
        lines.append("        SET title = EXCLUDED.title,")
        lines.append("            description = EXCLUDED.description,")
        lines.append("            instructions = EXCLUDED.instructions,")
        lines.append("            duration_seconds = EXCLUDED.duration_seconds,")
        lines.append("            position = EXCLUDED.position,")
        lines.append("            is_published = EXCLUDED.is_published,")
        lines.append("            updated_at = now();")
        lines.append("")
        lines.append("    DELETE FROM test_sections WHERE test_id = v_test_id;")
        lines.append("")

        # One continuous audio file for the whole test — every section row
        # below points at this same URL.
        audio_key = f"{num}:{test['audio_local']}"
        audio_url = urls.get(audio_key)
        if audio_url is None and audio_key not in missing_assets:
            missing_assets.append(audio_key)

        for section in test["sections"]:
            sid = section_uuid(num, section["key"])

            image_url = None
            if section.get("image_local"):
                image_key = f"{num}:{section['image_local']}"
                image_url = urls.get(image_key)
                if image_url is None:
                    missing_assets.append(image_key)

            lines.append(f"    -- {section['title']}")
            lines.append(f"    v_section_id := {sql_quote(sid)};")
            if image_url is not None or section.get("image_local"):
                lines.append("    INSERT INTO test_sections (id, test_id, position, title, instructions, audio_url, image_url)")
                lines.append("    VALUES (")
                lines.append("        v_section_id, v_test_id,")
                lines.append(f"        {section['position']}, {sql_quote(section['title'])}, {sql_quote(section['instructions'])},")
                if audio_url is None:
                    lines.append(f"        NULL, -- TODO: {audio_key} not uploaded yet")
                else:
                    lines.append(f"        {sql_quote(audio_url)},")
                if image_url is None:
                    lines.append(f"        NULL -- TODO: {section['image_local']} not uploaded yet")
                else:
                    lines.append(f"        {sql_quote(image_url)}")
                lines.append("    );")
            else:
                lines.append("    INSERT INTO test_sections (id, test_id, position, title, instructions, audio_url)")
                lines.append("    VALUES (")
                lines.append("        v_section_id, v_test_id,")
                lines.append(f"        {section['position']}, {sql_quote(section['title'])}, {sql_quote(section['instructions'])},")
                if audio_url is None:
                    lines.append(f"        NULL -- TODO: {audio_key} not uploaded yet")
                else:
                    lines.append(f"        {sql_quote(audio_url)}")
                lines.append("    );")
            lines.append("")

            for q in section["questions"]:
                lines.append("    v_qid := uuid_generate_v4();")
                opts = options_jsonb(q.get("options"))
                max_words = q.get("max_words")
                cols = ["id", "section_id", "qnumber", "position", "type", "prompt"]
                vals = [
                    "v_qid", "v_section_id", str(q["qnumber"]),
                    str(q["qnumber"]), sql_quote(q["type"]), sql_quote(q["prompt"]),
                ]
                if opts != "NULL":
                    cols.append("options")
                    vals.append(opts)
                if max_words is not None:
                    cols.append("max_words")
                    vals.append(str(max_words))
                lines.append(f"    INSERT INTO test_questions ({', '.join(cols)})")
                lines.append(f"      VALUES ({', '.join(vals)});")
                accepted_json = json.dumps(q["accepted"])
                lines.append(f"    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, {sql_quote(accepted_json)});")
            lines.append("")

        lines.append("END $$;")
        lines.append("")

    lines.append("COMMIT;")

    OUT_PATH.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {OUT_PATH} ({len(manifest['tests'])} tests, {sum(len(s['questions']) for t in manifest['tests'] for s in t['sections'])} questions)")

    if missing_assets:
        print(f"\n{len(missing_assets)} asset URL(s) still missing (seeded as NULL with a TODO comment):")
        for key in missing_assets:
            print(f"  - {key}")
        print("\nUpload the corresponding files and re-run upload-to-r2.mjs, then re-run this script to fill them in.")
    else:
        print("\nAll audio/image URLs resolved — no NULLs in the generated SQL.")


if __name__ == "__main__":
    main()
