#!/usr/bin/env python3
"""
Generates migrations/0027_seed_listening_tests_01_02.sql from
new-tests-manifest.json, following the exact same conventions as
scripts/r2-listening-seed/generate_seed_sql.py (tests 11-14):
  * 1 row in `tests` per mock test (skill='listening')
  * `test_sections` rows carry audio_url / image_url
  * `test_questions.options` uses [{"letter":"A","text":"..."}]
  * `test_answers.accepted` stores letter answers lowercase.

Uses a NAMESPACE distinct from 44444444-... (tests 11-14) and from the
writing bank's 22222222-... so ids never collide.
"""
import json
import uuid
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent.parent  # scripts/r2-listening-seed -> scripts -> repo root
OUT_PATH = ROOT / "migrations" / "0027_seed_listening_tests_01_02.sql"

NAMESPACE = uuid.UUID("55555555-5555-5555-5555-555555555555")


def test_uuid(num: int) -> str:
    return str(uuid.uuid5(NAMESPACE, f"listening-test-{num}"))


def section_uuid(num: int, key: str) -> str:
    return str(uuid.uuid5(NAMESPACE, f"listening-test-{num}-section-{key}"))


def sql_quote(s: str) -> str:
    return "'" + s.replace("'", "''") + "'"


def options_jsonb(options):
    if not options:
        return "NULL"
    return sql_quote(json.dumps(options)) + "::jsonb"


def main():
    # Reads from the repo's real manifest.json (tests 1 and 2 are merged in
    # there already, alongside 11-14) and filters down to just 1 and 2 --
    # there's no separate new-tests-manifest.json file in the repo.
    full_manifest = json.loads((HERE / "manifest.json").read_text(encoding="utf-8"))
    manifest = {"tests": [t for t in full_manifest["tests"] if t["num"] in (1, 2)]}
    urls_path = HERE / "asset-urls.json"
    urls = json.loads(urls_path.read_text(encoding="utf-8")) if urls_path.exists() else {}

    lines = []
    lines.append("-- =====================================================================")
    lines.append("-- Migration 0027 — Seed IELTS Listening Mock Tests 1-2")
    lines.append("-- Generated by scripts/r2-listening-seed/generate_seed_sql_01_02.py — do")
    lines.append("-- not hand-edit; re-run the generator instead if the source data changes.")
    lines.append("--")
    lines.append("-- Model (same as migrations/0024_seed_listening_tests_11_14.sql):")
    lines.append("--   * 1 row in `tests`         -> the mock test (skill='listening')")
    lines.append("--   * `test_sections` rows      -> one per question-type block")
    lines.append("--   * `test_questions`/`test_answers` -> all 40 questions + answer key")
    lines.append("--")
    lines.append("-- NOTE: audio_url / image_url are NULL with a TODO comment below until")
    lines.append("-- the corresponding files are uploaded to R2. To fill them in:")
    lines.append("--   1. Put the audio files here (repo root):")
    lines.append("--        scripts/r2-listening-seed/local_assets/TEST1/full.mp3")
    lines.append("--        scripts/r2-listening-seed/local_assets/TEST2/full.mp3")
    lines.append("--      (already committed for you)")
    lines.append("--   2. node --env-file=.env scripts/r2-listening-seed/upload-to-r2.mjs")
    lines.append("--   3. re-run this generator, then re-run this migration.")
    lines.append("--")
    lines.append('-- Run: psql -U postgres -d nexted_ielts -f migrations/0027_seed_listening_tests_01_02.sql')
    lines.append("-- Idempotent: re-running replaces each test's sections/questions cleanly.")
    lines.append("-- =====================================================================")
    lines.append("")
    lines.append("BEGIN;")
    lines.append("")
    lines.append("SET client_encoding = 'UTF8';")
    lines.append("")

    missing_assets = []

    for test in manifest["tests"]:
        num = test["num"]
        tid = test_uuid(num)
        title = test["title"]
        description = test["description"]
        instructions = (
            "You will hear the recording once. Answer all 40 questions as you "
            "listen. Complete the notes and choose the correct letters as "
            "instructed in each section."
        )

        lines.append(f"-- ---- Mock Test {num} " + "-" * max(0, 50 - len(str(num))))
        lines.append("DO $$")
        lines.append("DECLARE")
        lines.append(f"    v_test_id UUID := {sql_quote(tid)};")
        lines.append("    v_section_id UUID;")
        lines.append("    v_qid UUID;")
        lines.append("BEGIN")
        lines.append("    INSERT INTO tests (id, skill, title, description, instructions, duration_seconds, position, is_published)")
        lines.append("    VALUES (")
        lines.append("        v_test_id,")
        lines.append("        'listening',")
        lines.append(f"        {sql_quote(title)},")
        lines.append(f"        {sql_quote(description)},")
        lines.append(f"        {sql_quote(instructions)},")
        lines.append(f"        {test['duration_seconds']},")
        lines.append(f"        {num},")
        lines.append("        TRUE")
        lines.append("    )")
        lines.append("    ON CONFLICT (id) DO UPDATE")
        lines.append("        SET title = EXCLUDED.title,")
        lines.append("            description = EXCLUDED.description,")
        lines.append("            instructions = EXCLUDED.instructions,")
        lines.append("            duration_seconds = EXCLUDED.duration_seconds,")
        lines.append("            position = EXCLUDED.position,")
        lines.append("            is_published = EXCLUDED.is_published,")
        lines.append("            updated_at = now();")
        lines.append("")
        lines.append("    DELETE FROM test_sections WHERE test_id = v_test_id;")
        lines.append("")

        audio_key = f"{num}:{test['audio_local']}"
        audio_url = urls.get(audio_key)
        if audio_url is None and audio_key not in missing_assets:
            missing_assets.append(audio_key)

        for section in test["sections"]:
            sid = section_uuid(num, section["key"])

            image_url = None
            if section.get("image_local"):
                image_key = f"{num}:{section['image_local']}"
                image_url = urls.get(image_key)
                if image_url is None:
                    missing_assets.append(image_key)

            lines.append(f"    -- {section['title']}")
            lines.append(f"    v_section_id := {sql_quote(sid)};")
            if section.get("image_local"):
                lines.append("    INSERT INTO test_sections (id, test_id, position, title, instructions, audio_url, image_url)")
                lines.append("    VALUES (")
                lines.append("        v_section_id, v_test_id,")
                lines.append(f"        {section['position']}, {sql_quote(section['title'])}, {sql_quote(section['instructions'])},")
                if audio_url is None:
                    lines.append(f"        NULL, -- TODO: {audio_key} not uploaded yet")
                else:
                    lines.append(f"        {sql_quote(audio_url)},")
                if image_url is None:
                    lines.append(f"        NULL -- TODO: {section['image_local']} not uploaded yet")
                else:
                    lines.append(f"        {sql_quote(image_url)}")
                lines.append("    );")
            else:
                lines.append("    INSERT INTO test_sections (id, test_id, position, title, instructions, audio_url)")
                lines.append("    VALUES (")
                lines.append("        v_section_id, v_test_id,")
                lines.append(f"        {section['position']}, {sql_quote(section['title'])}, {sql_quote(section['instructions'])},")
                if audio_url is None:
                    lines.append(f"        NULL -- TODO: {audio_key} not uploaded yet")
                else:
                    lines.append(f"        {sql_quote(audio_url)}")
                lines.append("    );")
            lines.append("")

            for q in section["questions"]:
                lines.append("    v_qid := uuid_generate_v4();")
                opts = options_jsonb(q.get("options"))
                max_words = q.get("max_words")
                cols = ["id", "section_id", "qnumber", "position", "type", "prompt"]
                vals = [
                    "v_qid", "v_section_id", str(q["qnumber"]),
                    str(q["qnumber"]), sql_quote(q["type"]), sql_quote(q["prompt"]),
                ]
                if opts != "NULL":
                    cols.append("options")
                    vals.append(opts)
                if max_words is not None:
                    cols.append("max_words")
                    vals.append(str(max_words))
                lines.append(f"    INSERT INTO test_questions ({', '.join(cols)})")
                lines.append(f"      VALUES ({', '.join(vals)});")
                accepted_json = json.dumps(q["accepted"])
                lines.append(f"    INSERT INTO test_answers (question_id, accepted) VALUES (v_qid, {sql_quote(accepted_json)});")
            lines.append("")

        lines.append("END $$;")
        lines.append("")

    lines.append("COMMIT;")

    OUT_PATH.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {OUT_PATH} ({len(manifest['tests'])} tests, {sum(len(s['questions']) for t in manifest['tests'] for s in t['sections'])} questions)")

    if missing_assets:
        print(f"\n{len(missing_assets)} asset URL(s) missing (seeded as NULL with a TODO comment):")
        for key in missing_assets:
            print(f"  - {key}")
    else:
        print("\nAll audio/image URLs resolved.")


if __name__ == "__main__":
    main()
